<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { CircleAlert, RotateCcw } from 'lucide-vue-next'
import WorkspaceLayout from '@/components/WorkspaceLayout.vue'
import { ApiError } from '@/api/http'
import { adminRefundPayment } from '@/api/payment'
import { getAdminPayments } from '@/api/admin-extended'
const items=ref<Record<string,unknown>[]>([]);const status=ref('');const loading=ref(true);const errorMessage=ref('');const notice=ref('');const load=async()=>{try{const data=await getAdminPayments({status:status.value?Number(status.value):undefined});items.value=(data.items as Record<string,unknown>[])||[]}catch(e){errorMessage.value=e instanceof ApiError?e.message:'支付记录加载失败，请稍后重试。'}finally{loading.value=false}};const refund=async(id:number)=>{if(!window.confirm('确定退款这笔支付吗？'))return;try{await adminRefundPayment(id);notice.value='退款已提交';await load()}catch(e){errorMessage.value=e instanceof ApiError?e.message:'退款失败，请稍后重试。'}};const label=(s:number)=>s===1?'待支付':s===2?'成功':s===5?'已退款':'其他';onMounted(load)
</script>
<template><WorkspaceLayout role="admin"><div class="page"><header><p>支付管理</p><h1>支付记录</h1></header><div class="toolbar"><select v-model="status" @change="load"><option value="">全部状态</option><option value="2">成功</option><option value="5">已退款</option></select></div><div v-if="notice" class="notice success">{{notice}}</div><div v-if="errorMessage" class="notice error"><CircleAlert :size="16"/>{{errorMessage}}</div><div v-if="loading" class="state">正在加载支付记录…</div><div v-else-if="!items.length" class="state">暂无支付记录。</div><div v-else class="list"><article v-for="item in items" :key="Number(item.id)"><div><strong>{{item.payment_no}}</strong><small>{{item.patient_name||'患者'}} · {{item.appointment_no||'预约'}} · ¥{{item.amount}} · {{label(Number(item.status))}}</small></div><button v-if="Number(item.status)===2" class="refund" type="button" @click="refund(Number(item.id))"><RotateCcw :size="15"/>退款</button></article></div></div></WorkspaceLayout></template>
<style scoped>.page{max-width:1000px}.page header{margin-bottom:20px}.page header p{color:var(--primary);font-size:12px;font-weight:700}.page h1{margin-top:8px;font-size:30px}.toolbar select{min-height:40px;padding:0 10px;border:1px solid var(--border-strong);border-radius:5px}.list{margin-top:16px;display:grid;gap:8px}.list article{padding:15px;display:flex;align-items:center;justify-content:space-between;gap:10px;background:var(--surface-strong);border:1px solid var(--border);border-radius:7px}.list strong,.list small{display:block}.list small{margin-top:5px;color:var(--muted);font-size:12px}.refund{min-height:34px;padding:0 10px;display:inline-flex;align-items:center;gap:5px;color:var(--danger);background:var(--danger-soft);border:0;border-radius:5px;cursor:pointer}.notice{margin-top:14px;padding:11px;display:flex;gap:7px;border-radius:6px}.success{color:#166534;background:#dcfce7}.error{color:var(--danger);background:var(--danger-soft)}.state{padding:40px;color:var(--muted)}</style>
