<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { Activity, CircleAlert, RefreshCw } from 'lucide-vue-next'
import WorkspaceLayout from '@/components/WorkspaceLayout.vue'
import { ApiError } from '@/api/http'
import { getAdminStatistics } from '@/api/admin-extended'
import { getSystemMetrics } from '@/api/system'
const data=ref<Record<string,unknown>>({});const loading=ref(true);const errorMessage=ref('');const labels:Record<string,string>={users:'用户',patients:'患者',doctors:'医生',departments:'科室',active_schedules:'有效排班',active_appointments:'有效预约',pending_outbox:'待发送通知',active_sessions:'活跃会话',today_appointments:'今日预约',today_completed_visits:'今日完成就诊',paid_amount:'已支付金额'};const metricLabel=(key:string)=>labels[key]||key;const load=async()=>{try{const [metrics,statistics]=await Promise.all([getSystemMetrics(),getAdminStatistics()]);data.value={...metrics,...statistics}}catch(e){errorMessage.value=e instanceof ApiError?e.message:'系统指标加载失败，请稍后重试。'}finally{loading.value=false}};onMounted(load)
</script>
<template><WorkspaceLayout role="admin"><div class="page"><header><p>系统维护</p><h1>系统指标</h1></header><button class="refresh" type="button" @click="load"><RefreshCw :size="16"/>刷新指标</button><div v-if="errorMessage" class="notice"><CircleAlert :size="16"/>{{errorMessage}}</div><div v-if="loading" class="state">正在加载指标…</div><div v-else class="grid"><article v-for="(value,key) in data" :key="key"><Activity :size="18"/><strong>{{value}}</strong><span>{{metricLabel(key)}}</span></article></div></div></WorkspaceLayout></template>
<style scoped>.page{max-width:1000px}.page header{margin-bottom:18px}.page header p{color:var(--primary);font-size:12px;font-weight:700}.page h1{margin-top:8px;font-size:30px}.refresh{min-height:40px;padding:0 12px;display:inline-flex;align-items:center;gap:6px;color:var(--primary);background:var(--surface-strong);border:1px solid var(--border-strong);border-radius:5px;cursor:pointer}.grid{margin-top:18px;display:grid;grid-template-columns:repeat(4,1fr);gap:10px}.grid article{padding:18px;background:var(--surface-strong);border:1px solid var(--border);border-radius:7px}.grid svg{color:var(--primary)}.grid strong,.grid span{display:block}.grid strong{margin-top:14px;font-family:var(--font-serif);font-size:25px}.grid span{margin-top:5px;color:var(--muted);font-size:12px}.notice{margin-top:16px;padding:11px;display:flex;gap:7px;color:var(--danger);background:var(--danger-soft);border-radius:6px}.state{padding:40px;color:var(--muted)}@media(max-width:900px){.grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:520px){.grid{grid-template-columns:1fr}}</style>
