<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { Check, CircleAlert, RefreshCw, Wrench } from 'lucide-vue-next'
import WorkspaceLayout from '@/components/WorkspaceLayout.vue'
import { ApiError } from '@/api/http'
import { getDataConsistency, repairDataConsistency } from '@/api/admin-extended'
const data=ref<Record<string,unknown>|null>(null);const loading=ref(true);const saving=ref(false);const errorMessage=ref('');const notice=ref('');const load=async()=>{try{data.value=await getDataConsistency()}catch(e){errorMessage.value=e instanceof ApiError?e.message:'一致性检查失败，请稍后重试。'}finally{loading.value=false}};const repair=async()=>{saving.value=true;try{data.value=await repairDataConsistency();notice.value=`修复完成，共处理 ${data.value.affected_rows||0} 条记录`}catch(e){errorMessage.value=e instanceof ApiError?e.message:'修复失败，请稍后重试。'}finally{saving.value=false}};onMounted(load)
</script>
<template><WorkspaceLayout role="admin"><div class="page"><header><p>系统维护</p><h1>数据一致性</h1><span>检查排班、时间段和支付记录是否存在异常。</span></header><div v-if="notice" class="notice success"><Check :size="16"/>{{notice}}</div><div v-if="errorMessage" class="notice error"><CircleAlert :size="16"/>{{errorMessage}}</div><div v-if="loading" class="state">正在检查数据…</div><template v-else-if="data"><div class="grid"><article><strong>{{data.schedule_booked_count_mismatch||0}}</strong><span>排班预约数不一致</span></article><article><strong>{{data.orphan_reserved_slots||0}}</strong><span>孤立占用时间段</span></article><article><strong>{{data.payment_status_mismatch||0}}</strong><span>支付状态不一致</span></article><article><strong>{{data.orphan_slots||0}}</strong><span>孤儿时间段记录</span></article></div><div class="actions"><button type="button" @click="load"><RefreshCw :size="16"/>重新检查</button><button class="primary" type="button" :disabled="saving" @click="repair"><Wrench :size="16"/>{{saving?'修复中':'修复异常数据'}}</button></div></template></div></WorkspaceLayout></template>
<style scoped>.page{max-width:900px}.page header{margin-bottom:24px}.page header p{color:var(--primary);font-size:12px;font-weight:700}.page h1{margin-top:8px;font-size:30px}.page header span{display:block;margin-top:9px;color:var(--muted);font-size:13px}.grid{display:grid;grid-template-columns:repeat(2,1fr);gap:12px}.grid article{padding:22px;background:var(--surface-strong);border:1px solid var(--border);border-radius:7px}.grid strong,.grid span{display:block}.grid strong{font-family:var(--font-serif);font-size:30px}.grid span{margin-top:7px;color:var(--muted);font-size:12px}.actions{margin-top:20px;display:flex;gap:10px}.actions button{min-height:42px;padding:0 14px;display:inline-flex;align-items:center;gap:7px;color:var(--primary);background:var(--surface-strong);border:1px solid var(--border-strong);border-radius:5px;cursor:pointer}.actions .primary{color:#fff;background:var(--primary);border-color:var(--primary)}.actions button:disabled{opacity:.6}.notice{margin-bottom:14px;padding:11px;display:flex;gap:7px;align-items:center;border-radius:6px}.notice.success{color:#166534;background:#dcfce7}.notice.error{color:var(--danger);background:var(--danger-soft)}.state{padding:40px;color:var(--muted);text-align:center}@media(max-width:620px){.grid{grid-template-columns:1fr}.actions{flex-direction:column}}</style>
