<script setup lang="ts">
import { reactive, ref } from 'vue'
import { ArrowLeft, CheckCircle2, CircleAlert, Eye, EyeOff, Save } from 'lucide-vue-next'
import { RouterLink, useRouter } from 'vue-router'
import WorkspaceLayout from '@/components/WorkspaceLayout.vue'
import { ApiError } from '@/api/http'
import { createAdminPharmacy } from '@/api/admin-extended'
const router=useRouter();const form=reactive({username:'',password:'',confirm:''});const saving=ref(false);const errorMessage=ref('');const success=ref(false);const show=ref(false);const valid=()=>{errorMessage.value='';if(!/^[A-Za-z0-9_]{4,50}$/.test(form.username.trim())){errorMessage.value='用户名需为4-50位字母、数字或下划线';return false}if(form.password.length<8||form.password!==form.confirm){errorMessage.value='请确认密码至少8位且两次输入一致';return false}return true};const submit=async()=>{if(!valid())return;saving.value=true;try{await createAdminPharmacy({username:form.username.trim(),password:form.password});success.value=true;form.password='';form.confirm=''}catch(e){errorMessage.value=e instanceof ApiError?e.message:'药房账户创建失败，请稍后重试。'}finally{saving.value=false}}
</script>
<template><WorkspaceLayout role="admin"><div class="page"><RouterLink class="back" to="/admin/users/accounts"><ArrowLeft :size="16"/>返回账户列表</RouterLink><header><p>账号管理</p><h1>新增药房账户</h1></header><section class="panel"><div v-if="success" class="success"><CheckCircle2 :size="40"/><h2>药房账户已创建</h2><p>新账户可以登录药房工作台处理处方。</p><button class="primary" type="button" @click="router.replace('/admin/users/accounts')">查看账户列表</button></div><form v-else @submit.prevent="submit"><div v-if="errorMessage" class="notice"><CircleAlert :size="16"/>{{errorMessage}}</div><label>登录用户名<input v-model="form.username" required placeholder="4-50 位字母、数字或下划线"/></label><label>初始密码<div class="password"><input v-model="form.password" :type="show?'text':'password'" required placeholder="至少 8 个字符"/><button type="button" @click="show=!show" title="显示或隐藏密码"><EyeOff v-if="show" :size="17"/><Eye v-else :size="17"/></button></div></label><label>确认密码<input v-model="form.confirm" type="password" required placeholder="再次输入初始密码"/></label><button class="primary" type="submit" :disabled="saving"><Save :size="16"/>{{saving?'创建中':'创建药房账户'}}</button></form></section></div></WorkspaceLayout></template>
<style scoped>.page{max-width:760px}.back{display:inline-flex;align-items:center;gap:7px;color:var(--primary);font-size:13px;text-decoration:none}.page header{margin:28px 0 22px}.page header p{color:var(--primary);font-size:12px;font-weight:700}.page h1{margin-top:8px;font-size:30px}.panel{padding:28px;background:var(--surface-strong);border:1px solid var(--border);border-radius:8px}.panel form{display:grid;gap:16px}.panel label{display:grid;gap:7px;color:var(--ink);font-size:12px;font-weight:650}.panel input{min-height:44px;padding:0 11px;background:var(--surface);border:1px solid var(--border-strong);border-radius:5px}.password{position:relative}.password input{width:100%;padding-right:42px}.password button{position:absolute;right:7px;top:50%;transform:translateY(-50%);display:grid;place-items:center;border:0;background:transparent;color:var(--muted);cursor:pointer}.primary{min-height:42px;padding:0 16px;display:inline-flex;align-items:center;justify-content:center;gap:7px;color:#fff;background:var(--primary);border:0;border-radius:5px;cursor:pointer}.primary:disabled{opacity:.6}.notice{padding:11px;display:flex;align-items:center;gap:7px;color:var(--danger);background:var(--danger-soft);border-radius:6px}.success{text-align:center;padding:35px}.success svg{color:var(--success)}.success h2{margin-top:16px;font-family:var(--font-serif)}.success p{margin:10px 0 18px;color:var(--muted);font-size:13px}</style>


