<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { ArrowLeft, CalendarDays, CircleAlert, Clock3, Pencil } from 'lucide-vue-next'
import { RouterLink, useRoute } from 'vue-router'
import WorkspaceLayout from '@/components/WorkspaceLayout.vue'
import { ApiError } from '@/api/http'
import { getAdminSchedule, getAdminSlots } from '@/api/admin'
import type { Schedule, Slot } from '@/types/user'
const route=useRoute();const schedule=ref<Schedule|null>(null);const slots=ref<Slot[]>([]);const loading=ref(true);const errorMessage=ref('')
const periodLabel=(value:number)=>({1:'上午',2:'下午',3:'晚上'}[value]||'其他');const statusLabel=(value:number)=>({0:'未开始',1:'可预约',2:'停诊',3:'已结束'}[value]||'未知');const available=computed(()=>slots.value.filter((slot)=>slot.status===0).length)
onMounted(async()=>{try{const id=Number(route.params.id);const [item,slotData]=await Promise.all([getAdminSchedule(id),getAdminSlots(id)]);schedule.value=item;slots.value=slotData}catch(error){errorMessage.value=error instanceof ApiError?error.message:'排班详情加载失败，请稍后重试。'}finally{loading.value=false}})
</script>
<template><WorkspaceLayout role="admin"><div class="page"><RouterLink class="back" to="/admin/schedules/list"><ArrowLeft :size="16" />返回排班列表</RouterLink><header><div><p>门诊安排</p><h1>排班详情</h1></div><div v-if="schedule" class="header-actions"><RouterLink class="edit-link" :to="`/admin/schedules/${schedule.id}/slots`"><Clock3 :size="15" />时间段</RouterLink><RouterLink class="edit-link" :to="`/admin/schedules/${schedule.id}/edit`"><Pencil :size="15" />编辑排班</RouterLink></div></header><div v-if="loading" class="state">正在加载排班…</div><div v-else-if="errorMessage" class="notice"><CircleAlert :size="16" />{{errorMessage}}</div><template v-else-if="schedule"><section class="summary"><div><span>日期</span><strong>{{schedule.schedule_date}}</strong></div><div><span>时段</span><strong>{{periodLabel(schedule.period)}} · {{schedule.start_time.slice(0,5)}}—{{schedule.end_time.slice(0,5)}}</strong></div><div><span>医生编号</span><strong>{{schedule.doctor_id}}</strong></div><div><span>科室编号</span><strong>{{schedule.department_id}}</strong></div><div><span>号源</span><strong>{{schedule.booked_count}} / {{schedule.total_count}}</strong></div><div><span>状态</span><strong>{{statusLabel(schedule.status)}}</strong></div></section><section class="slot-section"><div class="slot-head"><h2>时间段</h2><span>{{available}} 个可预约</span></div><div v-if="!slots.length" class="state">暂无时间段。</div><div v-else class="slots"><article v-for="slot in slots" :key="slot.id"><Clock3 :size="16" /><div><strong>第 {{slot.slot_no}} 号</strong><small>{{slot.start_time.slice(0,5)}}—{{slot.end_time.slice(0,5)}}</small></div><em :class="{busy:slot.status!==0}">{{slot.status===0?'可预约':slot.status===1?'已预约':'已锁定'}}</em></article></div></section></template></div></WorkspaceLayout></template>
<style scoped>
.page{max-width:900px}.back{display:inline-flex;align-items:center;gap:7px;color:var(--primary);font-size:13px;text-decoration:none}.page header{display:flex;justify-content:space-between;align-items:end;margin:28px 0 24px}.page header p{color:var(--primary);font-size:12px;font-weight:700}.page h1{margin-top:8px;font-size:30px}.header-actions{display:flex;gap:7px}.edit-link{min-height:36px;padding:0 11px;display:inline-flex;align-items:center;gap:6px;color:#fff;background:var(--primary);border-radius:5px;text-decoration:none;font-size:12px}.summary{display:grid;grid-template-columns:repeat(3,1fr);gap:1px;background:var(--border);border:1px solid var(--border);border-radius:8px;overflow:hidden}.summary div{padding:18px;background:var(--surface-strong)}.summary span,.summary strong{display:block}.summary span{color:var(--muted);font-size:12px}.summary strong{margin-top:6px;font-size:14px}.slot-section{margin-top:26px}.slot-head{display:flex;justify-content:space-between;align-items:center}.slot-head h2{font-size:18px}.slot-head span{color:var(--muted);font-size:12px}.slots{margin-top:12px;display:grid;grid-template-columns:repeat(2,1fr);gap:9px}.slots article{padding:14px;display:flex;align-items:center;gap:10px;background:var(--surface-strong);border:1px solid var(--border);border-radius:7px}.slots article>svg{color:var(--primary)}.slots strong,.slots small{display:block}.slots small{margin-top:4px;color:var(--muted);font-size:12px}.slots em{margin-left:auto;color:#166534;font-size:12px;font-style:normal}.slots em.busy{color:var(--muted)}.state{padding:42px;color:var(--muted);text-align:center}.notice{padding:12px;display:flex;gap:8px;color:var(--danger);background:var(--danger-soft);border-radius:6px}@media(max-width:700px){.summary{grid-template-columns:repeat(2,1fr)}.slots{grid-template-columns:1fr}}@media(max-width:460px){.summary{grid-template-columns:1fr}.page header{align-items:flex-start;gap:12px;flex-direction:column}.header-actions{width:100%}.header-actions .edit-link{flex:1;justify-content:center}}
</style>
