<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { ArrowLeft, CircleAlert, Clock3, RotateCcw, Save, XCircle } from 'lucide-vue-next'
import { RouterLink, useRoute } from 'vue-router'
import WorkspaceLayout from '@/components/WorkspaceLayout.vue'
import { ApiError } from '@/api/http'
import { getAdminAppointment } from '@/api/adminAppointment'
import { cancelAdminAppointment, expireAdminAppointment, updateAdminAppointment } from '@/api/admin-extended'
import type { AppointmentRecord } from '@/types/user'
const route=useRoute();const item=ref<AppointmentRecord|null>(null);const loading=ref(true);const saving=ref(false);const errorMessage=ref('');const notice=ref('');const reason=ref('');const queueNo=ref(0);const remark=ref('');const statusLabel=(value:number)=>({1:'待支付',2:'已预约',3:'已签到',4:'就诊中',5:'已完成',6:'已取消',7:'医生停诊取消',8:'已过期',9:'已退款'}[value]||'处理中');
const load=async()=>{try{item.value=await getAdminAppointment(Number(route.params.id));queueNo.value=item.value.queue_no||0;remark.value=item.value.remark||''}catch(error){errorMessage.value=error instanceof ApiError?error.message:'预约详情加载失败，请稍后重试。'}finally{loading.value=false}};
const save=async()=>{saving.value=true;try{item.value=await updateAdminAppointment(Number(route.params.id),{queue_no:queueNo.value,remark:remark.value});notice.value='预约信息已保存'}catch(error){errorMessage.value=error instanceof ApiError?error.message:'预约保存失败，请稍后重试。'}finally{saving.value=false}};
const cancel=async()=>{if(!window.confirm('确定取消这条预约吗？'))return;try{await cancelAdminAppointment(Number(route.params.id),reason.value||undefined);notice.value='预约已取消';await load()}catch(error){errorMessage.value=error instanceof ApiError?error.message:'预约取消失败，请稍后重试。'}};
const expire=async()=>{if(!window.confirm('确定将这条预约标记为过期吗？'))return;try{await expireAdminAppointment(Number(route.params.id));notice.value='预约已标记为过期';await load()}catch(error){errorMessage.value=error instanceof ApiError?error.message:'预约过期处理失败，请稍后重试。'}};onMounted(load)
</script>
<template><WorkspaceLayout role="admin"><div class="page"><RouterLink class="back" to="/admin/appointments"><ArrowLeft :size="16"/>返回预约列表</RouterLink><header><p>业务查询</p><h1>预约详情</h1></header><div v-if="loading" class="state">正在加载详情…</div><div v-else-if="errorMessage" class="notice"><CircleAlert :size="16"/>{{errorMessage}}</div><template v-else-if="item"><div v-if="notice" class="notice success">{{notice}}</div><section class="card"><div><span>预约编号</span><strong>{{item.appointment_no||item.id}}</strong></div><div><span>患者</span><strong>{{item.patient_name||'未返回'}}</strong></div><div><span>医生</span><strong>{{item.doctor_name||'未返回'}}</strong></div><div><span>科室</span><strong>{{item.department_name||'未返回'}}</strong></div><div><span>日期</span><strong>{{item.appointment_date||'未填写'}}</strong></div><div><span>状态</span><strong>{{statusLabel(item.status)}}</strong></div><div><span>联系电话</span><strong>{{item.patient_phone||'未返回'}}</strong></div></section><form class="edit" @submit.prevent="save"><label>队列号<input v-model.number="queueNo" type="number" min="1"/></label><label>备注<textarea v-model="remark" rows="2"></textarea></label><button class="primary" type="submit" :disabled="saving"><Save :size="16"/>保存修改</button></form><div class="actions"><input v-model="reason" placeholder="取消原因（可选）"/><button class="danger" type="button" @click="cancel"><XCircle :size="16"/>取消预约</button><button class="warning" type="button" @click="expire"><Clock3 :size="16"/>标记过期</button><RouterLink class="refund" to="/admin/payments/refund"><RotateCcw :size="16"/>退款处理</RouterLink><RouterLink class="migrate" :to="`/admin/appointments/${route.params.id}/migrate`"><Clock3 :size="16"/>调整预约</RouterLink></div></template></div></WorkspaceLayout></template>
<style scoped>.page{max-width:900px}.back{display:inline-flex;align-items:center;gap:7px;color:#2563eb;font-size:13px;text-decoration:none}.page header{margin:28px 0 24px}.page header p{color:#2563eb;font-size:12px;font-weight:700}.page h1{margin-top:8px;font-size:30px}.card{padding:24px;display:grid;grid-template-columns:repeat(2,1fr);gap:18px;background:#fff;border:1px solid #e2e8f0;border-radius:8px}.card div{display:grid;gap:6px}.card span{color:#64748b;font-size:12px}.card strong{font-size:14px}.edit{margin-top:14px;padding:18px;display:grid;grid-template-columns:180px 1fr auto;gap:12px;align-items:end;background:#fff;border:1px solid #e2e8f0;border-radius:8px}.edit label{display:grid;gap:6px;color:#475569;font-size:12px}.edit input,.edit textarea,.actions input{min-height:38px;padding:0 10px;background:#f8fafc;border:1px solid #dbe3ec;border-radius:5px}.edit textarea{padding-top:9px}.primary,.danger,.warning,.refund,.migrate{min-height:38px;padding:0 13px;display:inline-flex;align-items:center;justify-content:center;gap:6px;border:0;border-radius:5px;cursor:pointer;text-decoration:none}.primary{color:#fff;background:#2563eb}.danger{color:#b91c1c;background:#fee2e2}.warning{color:#92400e;background:#fef3c7}.refund,.migrate{color:#fff;background:#2563eb}.migrate{background:#0f766e}.actions{margin-top:14px;display:flex;gap:8px;align-items:center}.actions input{flex:1}.state{padding:48px;color:#64748b;text-align:center}.notice{padding:12px;display:flex;gap:8px;align-items:center;color:#b91c1c;background:#fee2e2;border-radius:7px}.notice.success{color:#166534;background:#dcfce7}@media(max-width:620px){.card{grid-template-columns:1fr}.edit{grid-template-columns:1fr}.actions{align-items:stretch;flex-wrap:wrap}.actions input{flex-basis:100%}}
</style>
