<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { ArrowLeft, Check, CircleAlert, Save } from 'lucide-vue-next'
import { RouterLink, useRoute, useRouter } from 'vue-router'
import WorkspaceLayout from '@/components/WorkspaceLayout.vue'
import { ApiError } from '@/api/http'
import { getAdminDepartments } from '@/api/department'
import { getAdminDoctor, updateAdminDoctor, updateAdminDoctorStatus } from '@/api/admin'
import type { Department } from '@/types/user'
const route=useRoute();const router=useRouter();const loading=ref(true);const saving=ref(false);const notice=ref('');const errorMessage=ref('');const departments=ref<Department[]>([]);const doctorId=Number(route.params.id);const form=reactive({department_id:0,real_name:'',title:'',specialty:'',introduction:'',avatar_url:'',consultation_fee:0,status:1})
onMounted(async()=>{try{const [departmentData,doctor]=await Promise.all([getAdminDepartments(),getAdminDoctor(doctorId)]);departments.value=departmentData;Object.assign(form,{real_name:doctor.real_name,title:doctor.title||'',specialty:doctor.specialty||'',introduction:doctor.introduction||'',avatar_url:doctor.avatar_url||'',consultation_fee:Number(doctor.consultation_fee||0),department_id:doctor.department_id,status:doctor.status})}catch(error){errorMessage.value=error instanceof ApiError?error.message:error instanceof Error?error.message:'医生资料加载失败，请稍后重试。'}finally{loading.value=false}})
const save=async()=>{notice.value='';errorMessage.value='';saving.value=true;try{await updateAdminDoctor(doctorId,{department_id:form.department_id,real_name:form.real_name,title:form.title,specialty:form.specialty,introduction:form.introduction,avatar_url:form.avatar_url,consultation_fee:form.consultation_fee});await updateAdminDoctorStatus(doctorId,form.status);notice.value='医生资料已保存';await router.replace('/admin/users/accounts')}catch(error){errorMessage.value=error instanceof ApiError?error.message:error instanceof Error?error.message:'保存失败，请稍后重试。'}finally{saving.value=false}}
</script>
<template><WorkspaceLayout role="admin"><div class="edit-page"><RouterLink class="back" to="/admin/users/accounts"><ArrowLeft :size="16" />返回账户列表</RouterLink><header><p>账号资料</p><h1>编辑医生资料</h1></header><div v-if="loading" class="state">正在加载资料…</div><template v-else><div v-if="notice" class="notice success"><Check :size="16" />{{notice}}</div><div v-if="errorMessage" class="notice error"><CircleAlert :size="16" />{{errorMessage}}</div><form class="form" @submit.prevent="save"><label>所属科室<select v-model.number="form.department_id"><option v-for="item in departments" :key="item.id" :value="item.id">{{item.name}}</option></select></label><label>执业状态<select v-model.number="form.status"><option :value="1">在岗</option><option :value="0">停诊</option></select></label><label>姓名<input v-model="form.real_name" required /></label><label>职称<input v-model="form.title" /></label><label>擅长方向<input v-model="form.specialty" /></label><label>挂号费<input v-model.number="form.consultation_fee" type="number" min="0" step="0.01" required /></label><label class="wide">个人简介<textarea v-model="form.introduction" rows="4"></textarea></label><label class="wide">头像地址<input v-model="form.avatar_url" /></label><button class="primary wide" type="submit" :disabled="saving"><Save :size="16" />{{saving?'保存中':'保存资料'}}</button></form></template></div></WorkspaceLayout></template>
<style scoped>.edit-page{max-width:960px}.back{display:inline-flex;align-items:center;gap:7px;color:#2563eb;font-size:13px;text-decoration:none}.edit-page header{margin:28px 0 24px}.edit-page header p{color:#2563eb;font-size:12px;font-weight:700}.edit-page h1{margin-top:8px;font-size:30px}.form{padding:26px;display:grid;grid-template-columns:repeat(2,1fr);gap:18px;background:#fff;border:1px solid #e2e8f0;border-radius:9px}.form label{display:grid;gap:7px;color:#475569;font-size:12px;font-weight:600}.form input,.form select,.form textarea{min-height:42px;padding:0 11px;background:#f8fafc;border:1px solid #dbe3ec;border-radius:6px}.form textarea{padding-top:10px;resize:vertical}.wide{grid-column:1/-1}.primary{min-height:44px;display:inline-flex;align-items:center;justify-content:center;gap:7px;color:#fff;background:#2563eb;border:0;border-radius:6px;cursor:pointer}.notice{margin-bottom:16px;padding:12px 14px;display:flex;gap:8px;align-items:center;border-radius:7px;font-size:13px}.notice.success{color:#166534;background:#dcfce7}.notice.error{color:#b91c1c;background:#fee2e2}.state{padding:48px;color:#64748b;text-align:center}@media(max-width:620px){.form{grid-template-columns:1fr;padding:18px}.wide{grid-column:auto}}
</style>
