<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { ArrowLeft, Check, CircleAlert, Save } from 'lucide-vue-next'
import { RouterLink, useRoute, useRouter } from 'vue-router'
import WorkspaceLayout from '@/components/WorkspaceLayout.vue'
import { ApiError } from '@/api/http'
import { getAdminPatient, updateAdminPatient } from '@/api/admin'
const route=useRoute();const router=useRouter();const loading=ref(true);const saving=ref(false);const notice=ref('');const errorMessage=ref('');const form=reactive({real_name:'',phone:'',address:'',emergency_contact:'',emergency_phone:''})
onMounted(async()=>{try{const patient=await getAdminPatient(Number(route.params.id));Object.assign(form,{real_name:patient.real_name,phone:patient.phone,address:patient.address||'',emergency_contact:patient.emergency_contact||'',emergency_phone:patient.emergency_phone||''})}catch(error){errorMessage.value=error instanceof ApiError?error.message:error instanceof Error?error.message:'患者资料加载失败，请稍后重试。'}finally{loading.value=false}})
const save=async()=>{notice.value='';errorMessage.value='';saving.value=true;try{await updateAdminPatient(Number(route.params.id),form);notice.value='患者资料已保存';await router.replace('/admin/users/accounts')}catch(error){errorMessage.value=error instanceof ApiError?error.message:error instanceof Error?error.message:'保存失败，请稍后重试。'}finally{saving.value=false}}
</script>
<template><WorkspaceLayout role="admin"><div class="edit-page"><RouterLink class="back" to="/admin/users/accounts"><ArrowLeft :size="16" />返回账户列表</RouterLink><header><p>账号资料</p><h1>编辑患者资料</h1></header><div v-if="loading" class="state">正在加载资料…</div><template v-else><div v-if="notice" class="notice success"><Check :size="16" />{{notice}}</div><div v-if="errorMessage" class="notice error"><CircleAlert :size="16" />{{errorMessage}}</div><form class="form" @submit.prevent="save"><label>姓名<input v-model="form.real_name" required /></label><label>联系电话<input v-model="form.phone" required /></label><label>联系地址<input v-model="form.address" /></label><label>紧急联系人<input v-model="form.emergency_contact" /></label><label>紧急电话<input v-model="form.emergency_phone" /></label><button class="primary" type="submit" :disabled="saving"><Save :size="16" />{{saving?'保存中':'保存资料'}}</button></form></template></div></WorkspaceLayout></template>
<style scoped>.edit-page{max-width:820px}.back{display:inline-flex;align-items:center;gap:7px;color:#2563eb;font-size:13px;text-decoration:none}.edit-page header{margin:28px 0 24px}.edit-page header p{color:#2563eb;font-size:12px;font-weight:700}.edit-page h1{margin-top:8px;font-size:30px}.form{padding:26px;display:grid;grid-template-columns:repeat(2,1fr);gap:18px;background:#fff;border:1px solid #e2e8f0;border-radius:9px}.form label{display:grid;gap:7px;color:#475569;font-size:12px;font-weight:600}.form input{min-height:42px;padding:0 11px;background:#f8fafc;border:1px solid #dbe3ec;border-radius:6px}.primary{grid-column:1/-1;min-height:44px;display:inline-flex;align-items:center;justify-content:center;gap:7px;color:#fff;background:#2563eb;border:0;border-radius:6px;cursor:pointer}.notice{margin-bottom:16px;padding:12px 14px;display:flex;gap:8px;align-items:center;border-radius:7px;font-size:13px}.notice.success{color:#166534;background:#dcfce7}.notice.error{color:#b91c1c;background:#fee2e2}.notice.info{color:#1e4f80;background:#e4f0fb}.state{padding:48px;color:#64748b;text-align:center}@media(max-width:620px){.form{grid-template-columns:1fr;padding:18px}.primary{grid-column:auto}}
</style>
