<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { ArrowLeft, Check, CircleAlert, Save } from 'lucide-vue-next'
import { RouterLink, useRoute, useRouter } from 'vue-router'
import WorkspaceLayout from '@/components/WorkspaceLayout.vue'
import { ApiError } from '@/api/http'
import { getAdminSchedule, updateAdminSchedule } from '@/api/admin'
import type { ScheduleRequest } from '@/types/user'
const route=useRoute();const router=useRouter();const loading=ref(true);const saving=ref(false);const notice=ref('');const errorMessage=ref('');const form=reactive<ScheduleRequest>({doctor_id:null,department_id:0,schedule_date:'',period:1,start_time:'08:00',end_time:'12:00',total_count:20,fee:0,remark:''})
onMounted(async()=>{try{const item=await getAdminSchedule(Number(route.params.id));Object.assign(form,{doctor_id:item.doctor_id,department_id:item.department_id,schedule_date:item.schedule_date,period:item.period,start_time:item.start_time.slice(0,5),end_time:item.end_time.slice(0,5),total_count:item.total_count,fee:item.fee,remark:item.remark||''})}catch(error){errorMessage.value=error instanceof ApiError?error.message:'排班详情加载失败，请稍后重试。'}finally{loading.value=false}})
const save=async()=>{saving.value=true;notice.value='';errorMessage.value='';try{await updateAdminSchedule(Number(route.params.id),form);notice.value='排班已保存';setTimeout(()=>router.replace(`/admin/schedules/${route.params.id}`),500)}catch(error){errorMessage.value=error instanceof ApiError?error.message:'排班保存失败，请稍后重试。'}finally{saving.value=false}}
</script>
<template><WorkspaceLayout role="admin"><div class="page"><RouterLink class="back" :to="`/admin/schedules/${route.params.id}`"><ArrowLeft :size="16" />返回排班详情</RouterLink><header><p>门诊安排</p><h1>编辑排班</h1></header><div v-if="loading" class="state">正在加载排班…</div><template v-else><div v-if="notice" class="notice success"><Check :size="16" />{{notice}}</div><div v-if="errorMessage" class="notice error"><CircleAlert :size="16" />{{errorMessage}}</div><form class="form" @submit.prevent="save"><label>医生编号<input v-model.number="form.doctor_id" type="number" min="1" required /></label><label>科室编号<input v-model.number="form.department_id" type="number" min="1" required /></label><label>排班日期<input v-model="form.schedule_date" type="date" required /></label><label>时段<select v-model.number="form.period"><option :value="1">上午</option><option :value="2">下午</option><option :value="3">晚上</option></select></label><label>开始时间<input v-model="form.start_time" type="time" required /></label><label>结束时间<input v-model="form.end_time" type="time" required /></label><label>总号源<input v-model.number="form.total_count" type="number" min="1" required /></label><label>挂号费<input v-model.number="form.fee" type="number" min="0" step="0.01" required /></label><label class="wide">备注<textarea v-model="form.remark" rows="3"></textarea></label><button class="primary wide" type="submit" :disabled="saving"><Save :size="16" />{{saving?'保存中':'保存排班'}}</button></form></template></div></WorkspaceLayout></template>
<style scoped>
.page{max-width:900px}.back{display:inline-flex;align-items:center;gap:7px;color:var(--primary);font-size:13px;text-decoration:none}.page header{margin:28px 0 24px}.page header p{color:var(--primary);font-size:12px;font-weight:700}.page h1{margin-top:8px;font-size:30px}.form{padding:26px;display:grid;grid-template-columns:repeat(2,1fr);gap:18px;background:var(--surface-strong);border:1px solid var(--border);border-radius:8px}.form label{display:grid;gap:7px;color:var(--ink);font-size:12px;font-weight:650}.form input,.form select,.form textarea{min-height:42px;padding:0 11px;background:var(--surface);border:1px solid var(--border-strong);border-radius:5px}.form textarea{padding-top:10px;resize:vertical}.wide{grid-column:1/-1}.primary{min-height:44px;display:inline-flex;align-items:center;justify-content:center;gap:7px;color:#fff;background:var(--primary);border:0;border-radius:5px;cursor:pointer}.primary:disabled{opacity:.6}.notice{margin-bottom:14px;padding:12px;display:flex;gap:8px;align-items:center;border-radius:6px}.success{color:#166534;background:#dcfce7}.error{color:var(--danger);background:var(--danger-soft)}.state{padding:45px;color:var(--muted);text-align:center}@media(max-width:620px){.form{grid-template-columns:1fr}.wide{grid-column:auto}}
</style>
