<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { CircleAlert, Save } from 'lucide-vue-next'
import WorkspaceLayout from '@/components/WorkspaceLayout.vue'
import { ApiError } from '@/api/http'
import { getSystemConfig, updateSystemConfig } from '@/api/system'
const items=ref<Record<string,unknown>[]>([]);const loading=ref(true);const saving=ref('');const errorMessage=ref('');const load=async()=>{try{items.value=await getSystemConfig()}catch(e){errorMessage.value=e instanceof ApiError?e.message:'系统参数加载失败，请稍后重试。'}finally{loading.value=false}};const save=async(item:Record<string,unknown>)=>{saving.value=String(item.config_key);try{const data=await updateSystemConfig(String(item.config_key),{config_value:String(item.config_value??''),description:String(item.description??'')});Object.assign(item,data)}catch(e){errorMessage.value=e instanceof ApiError?e.message:'参数保存失败，请稍后重试。'}finally{saving.value=''}};onMounted(load)
</script>
<template><WorkspaceLayout role="admin"><div class="page"><header><p>系统维护</p><h1>系统参数</h1></header><div v-if="errorMessage" class="notice"><CircleAlert :size="16"/>{{errorMessage}}</div><div v-if="loading" class="state">正在加载参数…</div><div v-else class="list"><form v-for="item in items" :key="String(item.config_key)" @submit.prevent="save(item)"><div><strong>{{item.config_key}}</strong><small>{{item.description||'系统运行参数'}}</small></div><input v-model="item.config_value"/><button class="icon" type="submit" :disabled="saving===String(item.config_key)" title="保存参数"><Save :size="15"/></button></form></div></div></WorkspaceLayout></template>
<style scoped>.page{max-width:900px}.page header{margin-bottom:22px}.page header p{color:var(--primary);font-size:12px;font-weight:700}.page h1{margin-top:8px;font-size:30px}.list{display:grid;gap:8px}.list form{padding:15px;display:grid;grid-template-columns:1fr 260px 36px;align-items:center;gap:12px;background:var(--surface-strong);border:1px solid var(--border);border-radius:7px}.list strong,.list small{display:block}.list small{margin-top:5px;color:var(--muted);font-size:12px}.list input{min-height:38px;padding:0 10px;background:var(--surface);border:1px solid var(--border-strong);border-radius:5px}.icon{width:34px;height:34px;display:grid;place-items:center;color:var(--primary);background:var(--primary-soft);border:1px solid var(--border);border-radius:5px;cursor:pointer}.notice{margin-bottom:14px;padding:11px;display:flex;gap:7px;color:var(--danger);background:var(--danger-soft);border-radius:6px}.state{padding:40px;color:var(--muted)}@media(max-width:700px){.list form{grid-template-columns:1fr}.icon{width:100%}}</style>
