<script setup lang="ts">
import { computed, reactive, ref } from 'vue'
import { ArrowLeft, Check, CircleAlert, Save } from 'lucide-vue-next'
import { RouterLink, useRouter } from 'vue-router'
import WorkspaceLayout from '@/components/WorkspaceLayout.vue'
import { ApiError } from '@/api/http'
import { createDepartment } from '@/api/department'
import { useAuth } from '@/stores/auth'
const router = useRouter(); const saving = ref(false); const errorMessage = ref(''); const notice = ref(''); const form = reactive({ parent_id: null as number | null, name: '', code: '', description: '', location: '', contact_phone: '', sort_no: 0, status: 1 })
const { currentUser } = useAuth()
const isAdmin = computed(() => currentUser.value?.primary_role === 'ADMIN' || currentUser.value?.role_codes.includes('ADMIN'))
const save = async () => { saving.value = true; errorMessage.value = ''; notice.value = ''; try { await createDepartment(form); notice.value = '科室已创建'; await router.replace(isAdmin.value ? '/admin/departments' : '/department/home') } catch (error) { errorMessage.value = error instanceof ApiError ? error.message : '科室创建失败，请稍后重试。' } finally { saving.value = false } }
</script>
<template><WorkspaceLayout :role="isAdmin ? 'admin' : 'department'"><div class="page"><RouterLink class="back" :to="isAdmin ? '/admin/departments' : '/department/home'"><ArrowLeft :size="16" />返回科室列表</RouterLink><header><p>科室管理</p><h1>新增科室</h1></header><div v-if="notice" class="notice success"><Check :size="16" />{{ notice }}</div><div v-if="errorMessage" class="notice error"><CircleAlert :size="16" />{{ errorMessage }}</div><form class="form" @submit.prevent="save"><label>上级科室编号<input v-model.number="form.parent_id" type="number" min="1" /></label><label>科室名称<input v-model="form.name" required maxlength="100" /></label><label>科室编码<input v-model="form.code" required maxlength="50" /></label><label>所在位置<input v-model="form.location" maxlength="255" /></label><label>联系电话<input v-model="form.contact_phone" maxlength="20" /></label><label>排序号<input v-model.number="form.sort_no" type="number" min="0" /></label><label>状态<select v-model.number="form.status"><option :value="1">启用</option><option :value="0">停用</option></select></label><label class="wide">科室介绍<textarea v-model="form.description" rows="4" maxlength="500"></textarea></label><button class="primary wide" type="submit" :disabled="saving"><Save :size="16" />{{ saving ? '保存中' : '创建科室' }}</button></form></div></WorkspaceLayout></template>
<style scoped>.page{max-width:900px}.back{display:inline-flex;align-items:center;gap:7px;color:#2563eb;font-size:13px;text-decoration:none}.page header{margin:28px 0 24px}.page header p{color:#2563eb;font-size:12px;font-weight:700}.page h1{margin-top:8px;font-size:30px}.form{padding:26px;display:grid;grid-template-columns:repeat(2,1fr);gap:18px;background:#fff;border:1px solid #e2e8f0;border-radius:8px}.form label{display:grid;gap:7px;color:#475569;font-size:12px;font-weight:600}.form input,.form select,.form textarea{min-height:42px;padding:0 11px;background:#f8fafc;border:1px solid #dbe3ec;border-radius:6px}.form textarea{padding-top:10px;resize:vertical}.wide{grid-column:1/-1}.primary{min-height:44px;display:inline-flex;align-items:center;justify-content:center;gap:7px;color:#fff;background:#2563eb;border:0;border-radius:6px;cursor:pointer}.primary:disabled{opacity:.6}.notice{margin-bottom:16px;padding:12px;display:flex;gap:8px;align-items:center;border-radius:7px}.notice.success{color:#166534;background:#dcfce7}.notice.error{color:#b91c1c;background:#fee2e2}@media(max-width:620px){.form{grid-template-columns:1fr;padding:18px}.wide{grid-column:auto}}</style>
