<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { Check, CircleAlert, Pencil, Play, Square } from 'lucide-vue-next'
import { RouterLink } from 'vue-router'
import WorkspaceLayout from '@/components/WorkspaceLayout.vue'
import { ApiError } from '@/api/http'
import { completeVisit, getDoctorAppointmentsPage, startVisit } from '@/api/clinical'
import { useAuth } from '@/stores/auth'
import type { AppointmentRecord } from '@/types/user'
const { currentUser } = useAuth()
const isAdmin = computed(() => currentUser.value?.role_codes.includes('ADMIN') || currentUser.value?.primary_role === 'ADMIN')
const items = ref<AppointmentRecord[]>([]); const page = ref(1); const total = ref(0); const pageSize = 20; const loading = ref(true); const errorMessage = ref(''); const notice = ref(''); const actionId = ref(0)
const statusLabel = (value: number) => ({ 1: '待支付', 2: '已预约', 3: '已签到', 4: '就诊中', 5: '已完成', 6: '已取消', 7: '医生停诊取消', 8: '已过期', 9: '已退款' }[value] || '处理中')
const load = async () => { if (isAdmin.value) { loading.value = false; return }; loading.value = true; try { const result = await getDoctorAppointmentsPage(page.value, pageSize); items.value = result.items; total.value = result.total } catch (error) { errorMessage.value = error instanceof ApiError ? error.message : '预约加载失败，请稍后重试。' } finally { loading.value = false } }
const act = async (id: number, type: 'start' | 'complete') => { actionId.value = id; errorMessage.value = ''; notice.value = ''; try { if (type === 'start') await startVisit(id); else await completeVisit(id); notice.value = type === 'start' ? '已开始就诊' : '就诊已完成'; await load() } catch (error) { errorMessage.value = error instanceof ApiError ? error.message : '操作失败，请稍后重试。' } finally { actionId.value = 0 } }
const pageCount = () => Math.max(1, Math.ceil(total.value / pageSize))
const changePage = (delta: number) => { const next = page.value + delta; if (next < 1 || next > pageCount()) return; page.value = next; void load() }
onMounted(load)
</script>
<template><WorkspaceLayout role="doctor"><div class="page"><p>医生服务</p><h1>预约处理</h1><div v-if="isAdmin" class="notice info"><CircleAlert :size="16" />管理员可以浏览医生页面；预约处理请使用管理工作台的预约查询。</div><template v-else><div v-if="notice" class="notice success"><Check :size="16" />{{ notice }}</div><div v-if="errorMessage" class="notice error"><CircleAlert :size="16" />{{ errorMessage }}</div><div v-if="loading" class="state">正在加载预约…</div><div v-else-if="!items.length" class="state">暂无预约记录。</div><div v-else class="list"><article v-for="item in items" :key="item.id"><div><strong>{{ item.appointment_no || `预约 ${item.id}` }}</strong><small>{{ item.patient_name || '患者' }} · {{ item.appointment_date || '未填写日期' }} · 队列 {{ item.queue_no || '—' }} · {{ statusLabel(item.status) }}</small></div><div class="actions"><RouterLink class="icon-button" :to="`/doctor/appointments/${item.id}/edit`" title="编辑预约"><Pencil :size="15" /></RouterLink><button v-if="item.status === 3" type="button" :disabled="actionId === item.id" @click="act(item.id, 'start')"><Play :size="15" />开始就诊</button><button v-if="item.status === 4" type="button" :disabled="actionId === item.id" @click="act(item.id, 'complete')"><Square :size="15" />完成就诊</button></div></article></div><div v-if="!loading && items.length" class="pagination"><button type="button" :disabled="page<=1" @click="changePage(-1)">上一页</button><span>第 {{ page }} / {{ pageCount() }} 页，共 {{ total }} 条</span><button type="button" :disabled="page>=pageCount()" @click="changePage(1)">下一页</button></div></template></div></WorkspaceLayout></template>
<style scoped>.page{max-width:1000px}.page>p{color:#2563eb;font-size:12px;font-weight:700}.page h1{margin-top:8px;font-size:30px}.list{margin-top:28px;display:grid;gap:10px}.list article{padding:16px;display:flex;align-items:center;justify-content:space-between;gap:14px;background:#fff;border:1px solid #e2e8f0;border-radius:8px}.list strong,.list small{display:block}.list small{margin-top:5px;color:#64748b;font-size:12px}.actions{display:flex;gap:7px}.icon-button{width:34px;height:34px;display:grid;place-items:center;color:#2563eb;background:#eff6ff;border:1px solid #bfdbfe;border-radius:6px}.actions button{min-height:34px;padding:0 11px;display:inline-flex;align-items:center;gap:6px;color:#fff;background:#2563eb;border:0;border-radius:5px;cursor:pointer;font-size:12px}.pagination{margin-top:18px;display:flex;justify-content:center;align-items:center;gap:12px;color:#64748b;font-size:12px}.pagination button{min-height:34px;padding:0 10px;background:#fff;border:1px solid #dbe3ec;border-radius:5px;cursor:pointer}.pagination button:disabled{opacity:.5}.state{padding:48px;color:#64748b;text-align:center}.notice{margin-top:18px;padding:12px;display:flex;gap:8px;align-items:center;border-radius:7px;font-size:13px}.notice.success{color:#166534;background:#dcfce7}.notice.error{color:#b91c1c;background:#fee2e2}.notice.info{color:#1e4f80;background:#e4f0fb}@media(max-width:620px){.list article{align-items:flex-start;flex-direction:column}.actions{width:100%}.actions button,.icon-button{flex:1;justify-content:center}}</style>


