<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { ArrowLeft, CalendarDays, Check, CircleAlert, Clock3, Pencil, Plus, Save, Square, Trash2 } from 'lucide-vue-next'
import { RouterLink } from 'vue-router'
import WorkspaceLayout from '@/components/WorkspaceLayout.vue'
import { ApiError } from '@/api/http'
import { getPublicDepartments } from '@/api/department'
import { createDoctorSchedule, deleteDoctorSchedule, getDoctorProfile, getDoctorSchedules, getDoctorSchedule, stopDoctorSchedule, updateDoctorSchedule } from '@/api/doctor'
import type { Department, Schedule, ScheduleRequest } from '@/types/user'
const departments=ref<Department[]>([]);const items=ref<Schedule[]>([]);const loading=ref(true);const saving=ref(false);const editingId=ref<number|null>(null);const notice=ref('');const errorMessage=ref('')
const form=reactive<ScheduleRequest>({department_id:0,schedule_date:'',period:1,start_time:'08:00',end_time:'12:00',total_count:20,fee:0,remark:''})
const periodLabel=(value:number)=>({1:'上午',2:'下午',3:'晚上'}[value]||'其他');const statusLabel=(value:number)=>({0:'未开始',1:'可预约',2:'停诊',3:'已结束'}[value]||'未知')
const load=async()=>{loading.value=true;try{const [profile,deps,schedules]=await Promise.all([getDoctorProfile(),getPublicDepartments(),getDoctorSchedules()]);departments.value=deps;items.value=schedules;if(!form.department_id)form.department_id=profile.department_id;form.fee=Number(profile.consultation_fee||0)}catch(error){errorMessage.value=error instanceof ApiError?error.message:'排班加载失败，请稍后重试。'}finally{loading.value=false}}
const reset=()=>{editingId.value=null;Object.assign(form,{department_id:departments.value[0]?.id||0,schedule_date:'',period:1,start_time:'08:00',end_time:'12:00',total_count:20,fee:form.fee,remark:''})}
const edit=async(item:Schedule)=>{try{const detail=await getDoctorSchedule(item.id);editingId.value=item.id;Object.assign(form,{department_id:detail.department_id,schedule_date:detail.schedule_date,period:detail.period,start_time:detail.start_time.slice(0,5),end_time:detail.end_time.slice(0,5),total_count:detail.total_count,fee:detail.fee,remark:detail.remark||''})}catch(error){errorMessage.value=error instanceof ApiError?error.message:'排班详情加载失败，请稍后重试。'}}
const save=async()=>{saving.value=true;notice.value='';errorMessage.value='';try{if(editingId.value)await updateDoctorSchedule(editingId.value,form);else await createDoctorSchedule(form);notice.value=editingId.value?'排班已更新':'排班已创建';await load();reset()}catch(error){errorMessage.value=error instanceof ApiError?error.message:'排班保存失败，请稍后重试。'}finally{saving.value=false}}
const stop=async(id:number)=>{if(!window.confirm('确定停诊并取消相关预约吗？'))return;try{await stopDoctorSchedule(id);notice.value='排班已停诊';await load()}catch(error){errorMessage.value=error instanceof ApiError?error.message:'停诊失败，请稍后重试。'}}
const remove=async(id:number)=>{if(!window.confirm('确定删除这条排班吗？'))return;try{await deleteDoctorSchedule(id);notice.value='排班已删除';await load()}catch(error){errorMessage.value=error instanceof ApiError?error.message:'删除失败，请稍后重试。'}}
onMounted(load)
</script>
<template><WorkspaceLayout role="doctor"><div class="page"><RouterLink class="back" to="/doctor/home"><ArrowLeft :size="16" />返回医生首页</RouterLink><header><p>门诊安排</p><h1>我的排班</h1></header><div v-if="notice" class="notice success"><Check :size="16" />{{notice}}</div><div v-if="errorMessage" class="notice error"><CircleAlert :size="16" />{{errorMessage}}</div><section class="panel"><div class="panel-title"><h2>{{editingId?'编辑排班':'新增排班'}}</h2><button v-if="editingId" type="button" @click="reset">取消编辑</button></div><form class="form" @submit.prevent="save"><label>科室<select v-model.number="form.department_id" required><option v-for="item in departments" :key="item.id" :value="item.id">{{item.name}}</option></select></label><label>日期<input v-model="form.schedule_date" type="date" required /></label><label>时段<select v-model.number="form.period"><option :value="1">上午</option><option :value="2">下午</option><option :value="3">晚上</option></select></label><label>开始时间<input v-model="form.start_time" type="time" required /></label><label>结束时间<input v-model="form.end_time" type="time" required /></label><label>总号源<input v-model.number="form.total_count" type="number" min="1" required /></label><label>挂号费<input v-model.number="form.fee" type="number" min="0" step="0.01" required /></label><label class="wide">备注<textarea v-model="form.remark" rows="2"></textarea></label><button class="primary wide" type="submit" :disabled="saving"><Save :size="16" />{{saving?'保存中':editingId?'保存排班':'创建排班'}}</button></form></section><section class="list-section"><h2>排班记录</h2><div v-if="loading" class="state">正在加载排班…</div><div v-else-if="!items.length" class="state">暂无排班。</div><div v-else class="list"><article v-for="item in items" :key="item.id"><span class="icon"><CalendarDays :size="18" /></span><div><strong>{{item.schedule_date}} · {{periodLabel(item.period)}}</strong><small>{{item.start_time.slice(0,5)}}—{{item.end_time.slice(0,5)}} · 号源 {{item.booked_count}}/{{item.total_count}} · {{statusLabel(item.status)}}</small></div><div class="actions"><RouterLink class="icon-button" :to="`/doctor/schedules/${item.id}/slots`" title="时间段管理"><Clock3 :size="15" /></RouterLink><button class="icon-button" type="button" title="编辑排班" @click="edit(item)"><Pencil :size="15" /></button><button v-if="item.status===1" class="icon-button warning" type="button" title="停诊" @click="stop(item.id)"><Square :size="15" /></button><button v-else class="icon-button danger" type="button" title="删除排班" @click="remove(item.id)"><Trash2 :size="15" /></button></div></article></div></section></div></WorkspaceLayout></template>
<style scoped>
.page{max-width:1000px}.back{display:inline-flex;align-items:center;gap:7px;color:var(--primary);font-size:13px;text-decoration:none}.page header{margin:28px 0 24px}.page header p{color:var(--primary);font-size:12px;font-weight:700}.page h1{margin-top:8px;font-size:30px}.panel{padding:22px;background:var(--surface-strong);border:1px solid var(--border);border-radius:8px}.panel-title{display:flex;justify-content:space-between;align-items:center}.panel-title h2,.list-section h2{font-size:18px}.panel-title button{color:var(--muted);background:none;border:0;cursor:pointer}.form{margin-top:16px;display:grid;grid-template-columns:repeat(2,1fr);gap:16px}.form label{display:grid;gap:7px;color:var(--ink);font-size:12px;font-weight:650}.form input,.form select,.form textarea{min-height:40px;padding:0 10px;background:var(--surface);border:1px solid var(--border-strong);border-radius:5px}.form textarea{padding-top:8px;resize:vertical}.wide{grid-column:1/-1}.primary{min-height:42px;display:inline-flex;align-items:center;justify-content:center;gap:7px;color:#fff;background:var(--primary);border:0;border-radius:5px;cursor:pointer}.primary:disabled{opacity:.6}.list-section{margin-top:28px}.list{margin-top:14px;display:grid;gap:9px}.list article{padding:15px;display:flex;align-items:flex-start;gap:11px;background:var(--surface-strong);border:1px solid var(--border);border-radius:7px}.icon{width:34px;height:34px;display:grid;place-items:center;color:var(--primary);background:var(--primary-soft);border-radius:5px}.list strong,.list small{display:block}.list small{margin-top:4px;color:var(--muted);font-size:12px}.actions{margin-left:auto;display:flex;gap:6px}.icon-button{width:32px;height:32px;display:grid;place-items:center;color:var(--primary);background:var(--primary-soft);border:1px solid var(--border);border-radius:5px;cursor:pointer}.warning{color:#92400e;background:#fef3c7}.danger{color:var(--danger);background:var(--danger-soft)}.notice{margin-bottom:14px;padding:11px;display:flex;gap:7px;align-items:center;border-radius:6px}.success{color:#166534;background:#dcfce7}.error{color:var(--danger);background:var(--danger-soft)}.state{padding:40px;color:var(--muted);text-align:center}@media(max-width:620px){.form{grid-template-columns:1fr}.wide{grid-column:auto}.list article{flex-wrap:wrap}.actions{width:100%;margin-left:45px}}
</style>
