<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { ArrowLeft, CircleAlert, Pencil, Save, Trash2 } from 'lucide-vue-next'
import { RouterLink, useRoute } from 'vue-router'
import WorkspaceLayout from '@/components/WorkspaceLayout.vue'
import { ApiError } from '@/api/http'
import { createDiagnosis, deleteDiagnosis, getDiagnoses, updateDiagnosis } from '@/api/clinical'
import type { DiagnosisRecord } from '@/types/user'
const route=useRoute();const visitId=Number(route.params.visitId);const items=ref<DiagnosisRecord[]>([]);const loading=ref(true);const saving=ref(false);const errorMessage=ref('');const notice=ref('');const editingId=ref(0);const form=reactive({diagnosis_name:'',diagnosis_code:'',diagnosis_type:1,remark:''})
const load=async()=>{try{items.value=await getDiagnoses(visitId,'doctor')}catch(error){errorMessage.value=error instanceof ApiError?error.message:'诊断记录加载失败，请稍后重试。'}finally{loading.value=false}}
const reset=()=>{editingId.value=0;Object.assign(form,{diagnosis_name:'',diagnosis_code:'',diagnosis_type:1,remark:''})}
const edit=(item:DiagnosisRecord)=>{editingId.value=item.id;Object.assign(form,{diagnosis_name:item.diagnosis_name,diagnosis_code:item.diagnosis_code||'',diagnosis_type:item.diagnosis_type,remark:item.remark||''})}
const save=async()=>{saving.value=true;errorMessage.value='';notice.value='';try{if(editingId.value)await updateDiagnosis(editingId.value,form);else await createDiagnosis(visitId,form);notice.value=editingId.value?'诊断已更新':'诊断已添加';reset();await load()}catch(error){errorMessage.value=error instanceof ApiError?error.message:'诊断保存失败，请稍后重试。'}finally{saving.value=false}}
const remove=async(id:number)=>{if(!window.confirm('确定删除这条诊断吗？'))return;try{await deleteDiagnosis(id);notice.value='诊断已删除';await load()}catch(error){errorMessage.value=error instanceof ApiError?error.message:'诊断删除失败，请稍后重试。'}}
onMounted(load)
</script>
<template><WorkspaceLayout role="doctor"><div class="page"><RouterLink class="back" to="/doctor/visits"><ArrowLeft :size="16"/>返回就诊记录</RouterLink><header><p>临床记录</p><h1>诊断管理</h1></header><div v-if="notice" class="notice success">{{notice}}</div><div v-if="errorMessage" class="notice error"><CircleAlert :size="16"/>{{errorMessage}}</div><form class="form" @submit.prevent="save"><label>诊断名称<input v-model="form.diagnosis_name" required maxlength="255"/></label><label>疾病编码<input v-model="form.diagnosis_code" maxlength="50"/></label><label>诊断类型<select v-model.number="form.diagnosis_type"><option :value="1">初步诊断</option><option :value="2">确诊</option></select></label><label class="wide">备注<textarea v-model="form.remark" rows="3" maxlength="500"></textarea></label><div class="form-actions"><button class="primary" type="submit" :disabled="saving"><Save :size="16"/>{{saving?'保存中':editingId?'保存修改':'添加诊断'}}</button><button v-if="editingId" class="secondary" type="button" @click="reset">取消编辑</button></div></form><div v-if="loading" class="state">正在加载诊断…</div><div v-else-if="!items.length" class="state">暂无诊断记录。</div><div v-else class="list"><article v-for="item in items" :key="item.id"><div><strong>{{item.diagnosis_name}}</strong><small>{{item.diagnosis_type===2?'确诊':'初步诊断'}} · {{item.diagnosis_code||'暂无编码'}} · {{item.remark||'暂无备注'}}</small></div><div class="actions"><button class="icon-button" type="button" title="编辑诊断" @click="edit(item)"><Pencil :size="15"/></button><button class="icon-button danger" type="button" title="删除诊断" @click="remove(item.id)"><Trash2 :size="15"/></button></div></article></div></div></WorkspaceLayout></template>
<style scoped>.page{max-width:980px}.back{display:inline-flex;align-items:center;gap:7px;color:#2563eb;text-decoration:none;font-size:13px}.page header{margin:28px 0 22px}.page header p{color:#2563eb;font-size:12px;font-weight:700}.page h1{margin-top:8px;font-size:30px}.form{padding:22px;display:grid;grid-template-columns:repeat(2,1fr);gap:14px;background:#fff;border:1px solid #e2e8f0;border-radius:8px}.form label{display:grid;gap:7px;color:#475569;font-size:12px;font-weight:600}.form input,.form select,.form textarea{min-height:40px;padding:0 10px;background:#f8fafc;border:1px solid #dbe3ec;border-radius:6px}.form textarea{padding-top:9px;resize:vertical}.wide{grid-column:1/-1}.form-actions{display:flex;gap:8px}.primary,.secondary{min-height:38px;padding:0 13px;display:inline-flex;align-items:center;gap:6px;border:0;border-radius:6px;cursor:pointer}.primary{color:#fff;background:#2563eb}.secondary{color:#334155;background:#e2e8f0}.list{margin-top:22px;display:grid;gap:9px}.list article{padding:15px;display:flex;justify-content:space-between;gap:12px;background:#fff;border:1px solid #e2e8f0;border-radius:7px}.list strong,.list small{display:block}.list small{margin-top:5px;color:#64748b;font-size:12px}.actions{display:flex;gap:6px}.icon-button{width:32px;height:32px;display:grid;place-items:center;color:#2563eb;background:#eff6ff;border:1px solid #bfdbfe;border-radius:6px;cursor:pointer}.icon-button.danger{color:#b91c1c;background:#fee2e2;border-color:#fecaca}.notice{margin-bottom:14px;padding:11px;display:flex;gap:7px;border-radius:6px}.notice.success{color:#166534;background:#dcfce7}.notice.error{color:#b91c1c;background:#fee2e2}.state{padding:38px;color:#64748b;text-align:center}@media(max-width:620px){.form{grid-template-columns:1fr}.wide{grid-column:auto}.form-actions{flex-wrap:wrap}}
</style>
