<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { ArrowLeft, CircleAlert, Pencil, Save, Send, Trash2 } from 'lucide-vue-next'
import { RouterLink, useRoute } from 'vue-router'
import WorkspaceLayout from '@/components/WorkspaceLayout.vue'
import { ApiError } from '@/api/http'
import { addPrescriptionItem, deletePrescriptionItem, getDoctorPrescription, updatePrescriptionItem, updatePrescriptionStatus } from '@/api/clinical'
import type { PrescriptionItem, PrescriptionRecord } from '@/types/user'
const route=useRoute();const item=ref<PrescriptionRecord|null>(null);const loading=ref(true);const saving=ref(false);const errorMessage=ref('');const notice=ref('');const editingId=ref(0);const form=reactive({drug_name:'',specification:'',dosage:'',frequency:'',days:1,quantity:1,remark:''})
const statusLabel=(status:number)=>status===1?'草稿':status===2?'已提交':'已取药'
const load=async()=>{try{item.value=await getDoctorPrescription(Number(route.params.id))}catch(error){errorMessage.value=error instanceof ApiError?error.message:'处方加载失败，请稍后重试。'}finally{loading.value=false}}
const reset=()=>{editingId.value=0;Object.assign(form,{drug_name:'',specification:'',dosage:'',frequency:'',days:1,quantity:1,remark:''})}
const edit=(entry:PrescriptionItem)=>{editingId.value=entry.id;Object.assign(form,{drug_name:entry.drug_name,specification:entry.specification||'',dosage:entry.dosage,frequency:entry.frequency,days:entry.days,quantity:entry.quantity,remark:entry.remark||''})}
const save=async()=>{saving.value=true;errorMessage.value='';try{if(editingId.value)await updatePrescriptionItem(editingId.value,form);else await addPrescriptionItem(Number(route.params.id),form);notice.value=editingId.value?'明细已更新':'药品明细已添加';reset();await load()}catch(error){errorMessage.value=error instanceof ApiError?error.message:'明细保存失败，请稍后重试。'}finally{saving.value=false}}
const remove=async(id:number)=>{if(!window.confirm('确定删除这条药品明细吗？'))return;try{await deletePrescriptionItem(id);await load()}catch(error){errorMessage.value=error instanceof ApiError?error.message:'明细删除失败，请稍后重试。'}}
const submit=async()=>{if(!item.value)return;saving.value=true;try{item.value=await updatePrescriptionStatus(item.value.id,2);notice.value='处方已提交'}catch(error){errorMessage.value=error instanceof ApiError?error.message:'处方提交失败，请稍后重试。'}finally{saving.value=false}}
onMounted(load)
</script>
<template><WorkspaceLayout role="doctor"><div class="page"><RouterLink class="back" to="/doctor/visits"><ArrowLeft :size="16"/>返回就诊记录</RouterLink><header><p>临床记录</p><h1>处方详情</h1></header><div v-if="loading" class="state">正在加载处方…</div><template v-else-if="item"><div v-if="notice" class="notice success">{{notice}}</div><div v-if="errorMessage" class="notice error"><CircleAlert :size="16"/>{{errorMessage}}</div><section class="summary"><div><span>处方编号</span><strong>{{item.prescription_no}}</strong></div><div><span>状态</span><strong>{{statusLabel(item.status)}}</strong></div></section><form v-if="item.status===1" class="form" @submit.prevent="save"><label>药品名称<input v-model="form.drug_name" required maxlength="255"/></label><label>规格<input v-model="form.specification" maxlength="100"/></label><label>单次用量<input v-model="form.dosage" required maxlength="100"/></label><label>用药频率<input v-model="form.frequency" required maxlength="100"/></label><label>用药天数<input v-model.number="form.days" type="number" min="1" required/></label><label>开具数量<input v-model.number="form.quantity" type="number" min="1" step="0.01" required/></label><label class="wide">备注<textarea v-model="form.remark" rows="2" maxlength="255"></textarea></label><div class="form-actions"><button class="primary" type="submit" :disabled="saving"><Save :size="16"/>{{editingId?'保存明细':'添加明细'}}</button><button v-if="editingId" class="secondary" type="button" @click="reset">取消编辑</button></div></form><div class="items"><div class="items-heading"><h2>药品明细</h2><button v-if="item.status===1" class="submit" type="button" :disabled="saving || !item.items.length" @click="submit"><Send :size="15"/>提交处方</button></div><div v-if="!item.items.length" class="state">暂无药品明细。</div><article v-for="entry in item.items" :key="entry.id"><div><strong>{{entry.drug_name}}</strong><small>{{entry.specification||'未填写规格'}} · {{entry.dosage}} · {{entry.frequency}} · {{entry.days}} 天 · {{entry.quantity}}</small></div><div v-if="item.status===1" class="actions"><button class="icon-button" type="button" title="编辑明细" @click="edit(entry)"><Pencil :size="15"/></button><button class="icon-button danger" type="button" title="删除明细" @click="remove(entry.id)"><Trash2 :size="15"/></button></div></article></div></template></div></WorkspaceLayout></template>
<style scoped>.page{max-width:1000px}.back{display:inline-flex;align-items:center;gap:7px;color:#2563eb;text-decoration:none;font-size:13px}.page header{margin:28px 0 22px}.page header p{color:#2563eb;font-size:12px;font-weight:700}.page h1{margin-top:8px;font-size:30px}.summary{padding:18px;display:flex;gap:38px;background:#fff;border:1px solid #e2e8f0;border-radius:8px}.summary span,.summary strong{display:block}.summary span{color:#64748b;font-size:12px}.summary strong{margin-top:5px}.form{margin-top:16px;padding:22px;display:grid;grid-template-columns:repeat(2,1fr);gap:14px;background:#fff;border:1px solid #e2e8f0;border-radius:8px}.form label{display:grid;gap:7px;color:#475569;font-size:12px;font-weight:600}.form input,.form textarea{min-height:40px;padding:0 10px;background:#f8fafc;border:1px solid #dbe3ec;border-radius:6px}.form textarea{padding-top:9px;resize:vertical}.wide{grid-column:1/-1}.form-actions,.items-heading,.actions{display:flex;gap:8px}.primary,.secondary,.submit{min-height:38px;padding:0 13px;display:inline-flex;align-items:center;gap:6px;border:0;border-radius:6px;cursor:pointer}.primary,.submit{color:#fff;background:#2563eb}.secondary{color:#334155;background:#e2e8f0}.items{margin-top:22px}.items-heading{align-items:center;justify-content:space-between}.items h2{font-size:19px}.items article{margin-top:9px;padding:15px;display:flex;justify-content:space-between;gap:12px;background:#fff;border:1px solid #e2e8f0;border-radius:7px}.items strong,.items small{display:block}.items small{margin-top:5px;color:#64748b;font-size:12px}.icon-button{width:32px;height:32px;display:grid;place-items:center;color:#2563eb;background:#eff6ff;border:1px solid #bfdbfe;border-radius:6px;cursor:pointer}.icon-button.danger{color:#b91c1c;background:#fee2e2;border-color:#fecaca}.notice{margin-bottom:14px;padding:11px;display:flex;gap:7px;border-radius:6px}.notice.success{color:#166534;background:#dcfce7}.notice.error{color:#b91c1c;background:#fee2e2}.state{padding:38px;color:#64748b;text-align:center}@media(max-width:620px){.summary{flex-wrap:wrap}.form{grid-template-columns:1fr}.wide{grid-column:auto}.items-heading{align-items:flex-start;flex-direction:column}}
</style>
