<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { CircleAlert, Eye, Search, UserRound } from 'lucide-vue-next'
import { RouterLink } from 'vue-router'
import WorkspaceLayout from '@/components/WorkspaceLayout.vue'
import { ApiError } from '@/api/http'
import { getDoctorPatients } from '@/api/clinical'
const keyword=ref('');const items=ref<Record<string,unknown>[]>([]);const loading=ref(true);const errorMessage=ref('');const load=async()=>{try{items.value=await getDoctorPatients(keyword.value)}catch(e){errorMessage.value=e instanceof ApiError?e.message:'患者列表加载失败，请稍后重试。'}finally{loading.value=false}};onMounted(load)
</script>
<template><WorkspaceLayout role="doctor"><div class="page"><header><p>患者服务</p><h1>我的患者</h1></header><form class="search" @submit.prevent="load"><input v-model="keyword" placeholder="姓名或手机号"/><button type="submit"><Search :size="16"/>查询</button></form><div v-if="errorMessage" class="notice"><CircleAlert :size="16"/>{{errorMessage}}</div><div v-if="loading" class="state">正在加载患者…</div><div v-else-if="!items.length" class="state">暂无相关患者。</div><div v-else class="list"><article v-for="item in items" :key="Number(item.id)"><UserRound :size="18"/><div><strong>{{item.real_name||item.patient_name}}</strong><small>{{item.phone||'未填写电话'}}</small></div><RouterLink class="icon" :to="`/doctor/patients/${item.id}`" title="查看患者"><Eye :size="15"/></RouterLink></article></div></div></WorkspaceLayout></template>
<style scoped>.page{max-width:900px}.page header{margin-bottom:22px}.page header p{color:var(--primary);font-size:12px;font-weight:700}.page h1{margin-top:8px;font-size:30px}.search{display:flex;gap:8px}.search input{flex:1;min-height:40px;padding:0 10px;border:1px solid var(--border-strong);border-radius:5px}.search button{min-height:40px;padding:0 13px;display:inline-flex;align-items:center;gap:6px;color:#fff;background:var(--primary);border:0;border-radius:5px;cursor:pointer}.list{margin-top:18px;display:grid;gap:8px}.list article{padding:14px;display:flex;align-items:center;gap:10px;background:var(--surface-strong);border:1px solid var(--border);border-radius:7px}.list article>svg{color:var(--primary)}.list strong,.list small{display:block}.list small{margin-top:4px;color:var(--muted);font-size:12px}.icon{margin-left:auto;width:32px;height:32px;display:grid;place-items:center;color:var(--primary);background:var(--primary-soft);border:1px solid var(--border);border-radius:5px}.notice{margin-top:14px;padding:11px;display:flex;gap:7px;color:var(--danger);background:var(--danger-soft);border-radius:6px}.state{padding:40px;color:var(--muted)}</style>
