<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { ArrowLeft, CircleAlert, ClipboardList, UserRound } from 'lucide-vue-next'
import { RouterLink, useRoute } from 'vue-router'
import WorkspaceLayout from '@/components/WorkspaceLayout.vue'
import { ApiError } from '@/api/http'
import { getDoctorPatient, getDoctorPatientHistory } from '@/api/clinical'
const route=useRoute();const patient=ref<Record<string,unknown>|null>(null);const history=ref<Record<string,unknown>|null>(null);const loading=ref(true);const errorMessage=ref('');onMounted(async()=>{try{const id=Number(route.params.id);[patient.value,history.value]=await Promise.all([getDoctorPatient(id),getDoctorPatientHistory(id)])}catch(e){errorMessage.value=e instanceof ApiError?e.message:'患者资料加载失败，请稍后重试。'}finally{loading.value=false}})
</script>
<template><WorkspaceLayout role="doctor"><div class="page"><RouterLink class="back" to="/doctor/patients"><ArrowLeft :size="16"/>返回我的患者</RouterLink><header><p>患者服务</p><h1>患者详情</h1></header><div v-if="loading" class="state">正在加载患者资料…</div><div v-else-if="errorMessage" class="notice"><CircleAlert :size="16"/>{{errorMessage}}</div><template v-else-if="patient"><section class="card"><UserRound :size="28"/><div><h2>{{patient.real_name||patient.patient_name}}</h2><p>联系电话：{{patient.phone||'未填写'}}</p><p>患者编号：{{patient.id}}</p></div></section><section class="history"><h2><ClipboardList :size="18"/>就诊历史</h2><pre>{{ JSON.stringify(history, null, 2) }}</pre></section></template></div></WorkspaceLayout></template>
<style scoped>.page{max-width:900px}.back{display:inline-flex;align-items:center;gap:7px;color:var(--primary);font-size:13px;text-decoration:none}.page header{margin:28px 0 22px}.page header p{color:var(--primary);font-size:12px;font-weight:700}.page h1{margin-top:8px;font-size:30px}.card{padding:22px;display:flex;gap:14px;align-items:flex-start;background:var(--surface-strong);border:1px solid var(--border);border-radius:8px}.card>svg{color:var(--primary)}.card h2{font-family:var(--font-serif);font-size:22px}.card p{margin-top:6px;color:var(--muted);font-size:13px}.history{margin-top:16px;padding:20px;background:var(--surface-strong);border:1px solid var(--border);border-radius:8px}.history h2{display:flex;align-items:center;gap:7px;font-size:18px}.history pre{margin-top:12px;padding:14px;overflow:auto;background:var(--surface);border-radius:5px;font:12px/1.6 var(--font-sans);white-space:pre-wrap}.notice{padding:11px;display:flex;gap:7px;color:var(--danger);background:var(--danger-soft);border-radius:6px}.state{padding:40px;color:var(--muted)}</style>
