<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { Check, CircleAlert, FilePlus2, Save, Stethoscope } from 'lucide-vue-next'
import { RouterLink } from 'vue-router'
import WorkspaceLayout from '@/components/WorkspaceLayout.vue'
import { ApiError } from '@/api/http'
import { getDoctorVisits, updateDoctorVisit } from '@/api/clinical'
import { useAuth } from '@/stores/auth'
import type { VisitRecord } from '@/types/user'
const { currentUser } = useAuth()
const isAdmin = computed(() => currentUser.value?.role_codes.includes('ADMIN') || currentUser.value?.primary_role === 'ADMIN')
const items = ref<VisitRecord[]>([]); const loading = ref(true); const savingId = ref(0); const notice = ref(''); const errorMessage = ref(''); const forms = reactive<Record<number, { chief_complaint: string; present_illness: string; medical_advice: string }>>({})
const statusLabel = (value: number) => ({ 1: '待就诊', 2: '就诊中', 3: '已完成' }[value] || '处理中')
const load = async () => { if (isAdmin.value) { loading.value = false; return }; try { items.value = await getDoctorVisits(); items.value.forEach((item) => { forms[item.id] = { chief_complaint: item.chief_complaint || '', present_illness: item.present_illness || '', medical_advice: item.medical_advice || '' } }) } catch (error) { errorMessage.value = error instanceof ApiError ? error.message : '就诊记录加载失败，请稍后重试。' } finally { loading.value = false } }
const save = async (item: VisitRecord) => { savingId.value = item.id; notice.value = ''; errorMessage.value = ''; try { const form = forms[item.id] || { chief_complaint: '', present_illness: '', medical_advice: '' }; const updated = await updateDoctorVisit(item.id, form); Object.assign(item, updated); notice.value = '就诊记录已保存' } catch (error) { errorMessage.value = error instanceof ApiError ? error.message : '保存失败，请稍后重试。' } finally { savingId.value = 0 } }
onMounted(load)
</script>
<template><WorkspaceLayout role="doctor"><div class="page"><p>临床记录</p><h1>就诊记录</h1><div v-if="isAdmin" class="notice info"><CircleAlert :size="16" />管理员可以浏览医生页面；就诊记录请使用医生账号查看。</div><template v-else><div v-if="notice" class="notice success"><Check :size="16" />{{ notice }}</div><div v-if="errorMessage" class="notice error"><CircleAlert :size="16" />{{ errorMessage }}</div><div v-if="loading" class="state">正在加载记录…</div><div v-else-if="!items.length" class="state">暂无就诊记录。</div><div v-else class="list"><article v-for="item in items" :key="item.id"><header><div><strong>{{ item.visit_no }}</strong><small>{{ item.patient_name || '患者' }} · {{ statusLabel(item.status) }}</small></div><div class="quick-actions"><RouterLink class="icon-button" :to="`/doctor/visits/${item.id}/diagnoses`" title="诊断管理"><Stethoscope :size="15" /></RouterLink><RouterLink class="icon-button" :to="`/doctor/visits/${item.id}/prescriptions/create`" title="创建处方"><FilePlus2 :size="15" /></RouterLink></div></header><form @submit.prevent="save(item)"><label>主诉<textarea v-model="forms[item.id].chief_complaint" :disabled="item.status === 3" rows="2"></textarea></label><label>现病史<textarea v-model="forms[item.id].present_illness" :disabled="item.status === 3" rows="2"></textarea></label><label>医嘱<textarea v-model="forms[item.id].medical_advice" :disabled="item.status === 3" rows="2"></textarea></label><button class="primary" type="submit" :disabled="item.status === 3 || savingId === item.id"><Save :size="16" />{{ savingId === item.id ? '保存中' : '保存记录' }}</button></form></article></div></template></div></WorkspaceLayout></template>
<style scoped>.page{max-width:1000px}.page>p{color:#2563eb;font-size:12px;font-weight:700}.page h1{margin-top:8px;font-size:30px}.list{margin-top:28px;display:grid;gap:14px}.list article{padding:20px;background:#fff;border:1px solid #e2e8f0;border-radius:8px}.list header{display:flex;justify-content:space-between}.list strong,.list small{display:block}.list small{margin-top:5px;color:#64748b;font-size:12px}.list form{margin-top:18px;display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.list label{display:grid;gap:6px;color:#475569;font-size:12px;font-weight:600}.list textarea{padding:9px;color:#1e293b;background:#f8fafc;border:1px solid #dbe3ec;border-radius:6px;resize:vertical}.primary{min-height:40px;display:inline-flex;align-items:center;justify-content:center;gap:7px;color:#fff;background:#2563eb;border:0;border-radius:6px;cursor:pointer}.primary:disabled{opacity:.6}.state{padding:48px;color:#64748b;text-align:center}.notice{margin-top:18px;padding:12px;display:flex;gap:8px;align-items:center;border-radius:7px;font-size:13px}.notice.success{color:#166534;background:#dcfce7}.notice.error{color:#b91c1c;background:#fee2e2}.notice.info{color:#1e4f80;background:#e4f0fb}@media(max-width:760px){.list form{grid-template-columns:1fr}}</style>
