<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { ArrowLeft, Check, CircleAlert, Save } from 'lucide-vue-next'
import { RouterLink } from 'vue-router'
import WorkspaceLayout from '@/components/WorkspaceLayout.vue'
import { ApiError } from '@/api/http'
import { getDoctorProfile, updateDoctorProfile } from '@/api/doctor'
const loading = ref(true); const saving = ref(false); const notice = ref(''); const errorMessage = ref('')
const form = reactive({ real_name: '', title: '', specialty: '', introduction: '', avatar_url: '', consultation_fee: 0 })
onMounted(async()=>{try{const profile=await getDoctorProfile();Object.assign(form,{real_name:profile.real_name,title:profile.title||'',specialty:profile.specialty||'',introduction:profile.introduction||'',avatar_url:profile.avatar_url||'',consultation_fee:Number(profile.consultation_fee||0)})}catch(error){errorMessage.value=error instanceof ApiError?error.message:'个人资料加载失败，请稍后重试。'}finally{loading.value=false}})
const save=async()=>{saving.value=true;notice.value='';errorMessage.value='';try{await updateDoctorProfile(form);notice.value='个人资料已保存'}catch(error){errorMessage.value=error instanceof ApiError?error.message:'保存失败，请稍后重试。'}finally{saving.value=false}}
</script>
<template><WorkspaceLayout role="doctor"><div class="page"><RouterLink class="back" to="/doctor/home"><ArrowLeft :size="16" />返回医生首页</RouterLink><header><p>个人信息</p><h1>个人资料</h1></header><div v-if="loading" class="state">正在加载资料…</div><template v-else><div v-if="notice" class="notice success"><Check :size="16" />{{notice}}</div><div v-if="errorMessage" class="notice error"><CircleAlert :size="16" />{{errorMessage}}</div><form class="form" @submit.prevent="save"><label>姓名<input v-model="form.real_name" required /></label><label>职称<input v-model="form.title" /></label><label>擅长方向<input v-model="form.specialty" /></label><label>挂号费<input v-model.number="form.consultation_fee" type="number" min="0" step="0.01" required /></label><label class="wide">个人简介<textarea v-model="form.introduction" rows="5"></textarea></label><label class="wide">头像地址<input v-model="form.avatar_url" /></label><button class="primary wide" type="submit" :disabled="saving"><Save :size="16" />{{saving?'保存中':'保存资料'}}</button></form></template></div></WorkspaceLayout></template>
<style scoped>
.page{max-width:900px}.back{display:inline-flex;align-items:center;gap:7px;color:var(--primary);font-size:13px;text-decoration:none}.page header{margin:28px 0 24px}.page header p{color:var(--primary);font-size:12px;font-weight:700}.page h1{margin-top:8px;font-size:30px}.form{padding:26px;display:grid;grid-template-columns:repeat(2,1fr);gap:18px;background:var(--surface-strong);border:1px solid var(--border);border-radius:8px}.form label{display:grid;gap:7px;color:var(--ink);font-size:12px;font-weight:650}.form input,.form textarea{min-height:42px;padding:0 11px;background:var(--surface);border:1px solid var(--border-strong);border-radius:5px}.form textarea{padding-top:10px;resize:vertical}.wide{grid-column:1/-1}.primary{min-height:44px;display:inline-flex;align-items:center;justify-content:center;gap:7px;color:#fff;background:var(--primary);border:0;border-radius:5px;cursor:pointer}.primary:disabled{opacity:.6}.notice{margin-bottom:14px;padding:12px;display:flex;gap:8px;align-items:center;border-radius:6px}.success{color:#166534;background:#dcfce7}.error{color:var(--danger);background:var(--danger-soft)}.state{padding:45px;color:var(--muted);text-align:center}@media(max-width:620px){.form{grid-template-columns:1fr}.wide{grid-column:auto}}
</style>
