<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { CircleAlert, FileText, Trash2, Upload } from 'lucide-vue-next'
import WorkspaceLayout from '@/components/WorkspaceLayout.vue'
import { ApiError } from '@/api/http'
import { deleteMedicalAttachment, getMedicalAttachments, uploadMedicalAttachment } from '@/api/attachment'
import { useAuth } from '@/stores/auth'
const { currentUser } = useAuth(); const layoutRole = computed<'doctor' | 'patient' | 'admin'>(() => currentUser.value?.primary_role === 'DOCTOR' ? 'doctor' : currentUser.value?.primary_role === 'PATIENT' ? 'patient' : 'admin'); const items = ref<Record<string, unknown>[]>([]); const loading = ref(true); const errorMessage = ref(''); const notice = ref(''); const file = ref<File | null>(null); const patientId = ref(currentUser.value?.patient_id || 0)
const load = async () => { try { items.value = await getMedicalAttachments(patientId.value ? { patient_id: patientId.value } : {}) } catch (error) { errorMessage.value = error instanceof ApiError ? error.message : '附件加载失败，请稍后重试。' } finally { loading.value = false } }
const handleFileChange = (event: Event) => { const input = event.target as HTMLInputElement; file.value = input.files?.[0] || null }
const upload = async () => { if (!file.value || !patientId.value) return; try { await uploadMedicalAttachment(file.value, patientId.value); notice.value = '附件已上传'; file.value = null; await load() } catch (error) { errorMessage.value = error instanceof ApiError ? error.message : '附件上传失败，请稍后重试。' } }
const remove = async (id: number) => { if (!window.confirm('确定删除这份附件吗？')) return; try { await deleteMedicalAttachment(id); notice.value = '附件已删除'; await load() } catch (error) { errorMessage.value = error instanceof ApiError ? error.message : '附件删除失败，请稍后重试。' } }
onMounted(load)
</script>
<template><WorkspaceLayout :role="layoutRole"><div class="page"><header><p>医疗资料</p><h1>检查附件</h1></header><div class="upload"><label v-if="currentUser?.primary_role === 'ADMIN'">患者编号<input v-model.number="patientId" type="number" min="1" /></label><label class="file"><span>选择文件</span><input type="file" @change="handleFileChange" /></label><button class="primary" type="button" :disabled="!file || !patientId" @click="upload"><Upload :size="16" />上传附件</button></div><div v-if="notice" class="notice success">{{ notice }}</div><div v-if="errorMessage" class="notice error"><CircleAlert :size="16" />{{ errorMessage }}</div><div v-if="loading" class="state">正在加载附件…</div><div v-else-if="!items.length" class="state">暂无附件记录。</div><div v-else class="list"><article v-for="item in items" :key="Number(item.id)"><FileText :size="19" /><div><strong>{{ item.original_name || '医疗附件' }}</strong><small>{{ item.attachment_type || '医疗记录' }} · {{ item.file_size || 0 }} bytes · {{ item.created_at || '' }}</small></div><button class="icon" type="button" title="删除附件" @click="remove(Number(item.id))"><Trash2 :size="15" /></button></article></div></div></WorkspaceLayout></template>
<style scoped>.page{max-width:1000px}.page header{margin-bottom:22px}.page header p{color:var(--primary);font-size:12px;font-weight:700}.page h1{margin-top:8px;font-size:30px}.upload{padding:16px;display:flex;align-items:end;gap:10px;background:var(--surface-strong);border:1px solid var(--border);border-radius:7px}.upload label{display:grid;gap:6px;color:var(--ink);font-size:12px;font-weight:650}.upload input[type=number]{min-height:38px;padding:0 9px;border:1px solid var(--border-strong);border-radius:5px}.primary{min-height:38px;padding:0 13px;display:inline-flex;align-items:center;gap:6px;color:#fff;background:var(--primary);border:0;border-radius:5px;cursor:pointer}.list{margin-top:16px;display:grid;gap:8px}.list article{padding:14px;display:flex;align-items:center;gap:10px;background:var(--surface-strong);border:1px solid var(--border);border-radius:7px}.list article>svg{color:var(--primary)}.list strong,.list small{display:block}.list small{margin-top:4px;color:var(--muted);font-size:12px}.icon{margin-left:auto;width:32px;height:32px;display:grid;place-items:center;color:var(--danger);background:var(--danger-soft);border:1px solid var(--border);border-radius:5px;cursor:pointer}.notice{margin-top:13px;padding:11px;display:flex;gap:7px;align-items:center;border-radius:6px}.success{color:#166534;background:#dcfce7}.error{color:var(--danger);background:var(--danger-soft)}.state{padding:40px;color:var(--muted)}@media(max-width:680px){.upload{align-items:stretch;flex-direction:column}}</style>
