<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { ArrowLeft, CircleAlert } from 'lucide-vue-next'
import { RouterLink, useRoute } from 'vue-router'
import { ApiError } from '@/api/http'
import { getDiagnoses, getPatientVisit } from '@/api/clinical'
import { useAuth } from '@/stores/auth'
import type { DiagnosisRecord, VisitRecord } from '@/types/user'
const route = useRoute(); const { currentUser } = useAuth(); const isAdmin = computed(() => currentUser.value?.role_codes.includes('ADMIN') || currentUser.value?.primary_role === 'ADMIN'); const item = ref<VisitRecord | null>(null); const diagnoses = ref<DiagnosisRecord[]>([]); const loading = ref(true); const errorMessage = ref('')
onMounted(async () => { if (isAdmin.value) { loading.value = false; return } try { const id = Number(route.params.id); [item.value, diagnoses.value] = await Promise.all([getPatientVisit(id), getDiagnoses(id, 'patient')]) } catch (error) { errorMessage.value = error instanceof ApiError ? error.message : '就诊详情加载失败，请稍后重试。' } finally { loading.value = false } })
</script>
<template><div class="page"><RouterLink class="back" to="/patient/visits"><ArrowLeft :size="16" />返回我的就诊</RouterLink><header><p>就诊记录</p><h1>就诊详情</h1></header><div v-if="isAdmin" class="notice info"><CircleAlert :size="16" />管理员可以浏览患者页面；就诊详情请由患者账号查看。</div><div v-else-if="loading" class="state">正在加载详情…</div><template v-else-if="item"><div v-if="errorMessage" class="notice"><CircleAlert :size="16" />{{ errorMessage }}</div><section class="card"><div><span>就诊编号</span><strong>{{ item.visit_no }}</strong></div><div><span>医生</span><strong>{{ item.doctor_name || '未返回' }}</strong></div><div><span>主诉</span><strong>{{ item.chief_complaint || '未填写' }}</strong></div><div><span>现病史</span><strong>{{ item.present_illness || '未填写' }}</strong></div><div class="wide"><span>医嘱</span><strong>{{ item.medical_advice || '未填写' }}</strong></div></section><section class="diagnoses"><h2>诊断记录</h2><div v-if="!diagnoses.length" class="state">暂无诊断记录。</div><div v-for="diagnosis in diagnoses" :key="diagnosis.id" class="diagnosis"><strong>{{ diagnosis.diagnosis_name }}</strong><span>{{ diagnosis.diagnosis_code || '暂无编码' }} · {{ diagnosis.remark || '暂无备注' }}</span></div></section></template></div></template>
<style scoped>.page{width:min(100% - 48px,820px);margin:0 auto;padding:72px 0 110px}.back{display:inline-flex;align-items:center;gap:7px;color:#2563eb;font-size:13px;text-decoration:none}.page header{margin:28px 0 24px}.page header p{color:#2563eb;font-size:12px;font-weight:700}.page h1{margin-top:8px;font-size:30px}.card{padding:24px;display:grid;grid-template-columns:repeat(2,1fr);gap:18px;background:#fff;border:1px solid #e2e8f0;border-radius:8px}.card div{display:grid;gap:6px}.card span{color:#64748b;font-size:12px}.card strong{font-size:14px}.wide{grid-column:1/-1}.diagnoses{margin-top:20px;padding:22px;background:#fff;border:1px solid #e2e8f0;border-radius:8px}.diagnoses h2{font-size:18px}.diagnosis{margin-top:12px;padding:12px;background:#f8fafc;border-radius:6px}.diagnosis strong,.diagnosis span{display:block}.diagnosis span{margin-top:5px;color:#64748b;font-size:12px}.state{padding:40px;color:#64748b;text-align:center}.notice{margin-bottom:16px;padding:12px;display:flex;gap:8px;align-items:center;color:#b91c1c;background:#fee2e2;border-radius:7px}.notice.info{color:#1e4f80;background:#e4f0fb}@media(max-width:620px){.card{grid-template-columns:1fr}.wide{grid-column:auto}}</style>
