<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { ArrowLeft, CircleAlert, CreditCard, LogIn, RotateCcw, Search } from 'lucide-vue-next'
import { RouterLink, useRoute } from 'vue-router'
import { ApiError } from '@/api/http'
import { cancelPatientAppointment, checkInPatientAppointment, getPatientAppointment } from '@/api/appointment'
import { getAppointmentPayment, getPayment, payAppointment, refundPayment } from '@/api/payment'
import { useAuth } from '@/stores/auth'
import type { AppointmentRecord, PaymentRecord } from '@/types/user'
const route = useRoute(); const { currentUser } = useAuth(); const isAdmin = computed(() => currentUser.value?.role_codes.includes('ADMIN') || currentUser.value?.primary_role === 'ADMIN'); const item = ref<AppointmentRecord | null>(null); const payment = ref<PaymentRecord | null>(null); const paymentId = ref(''); const loading = ref(true); const saving = ref(false); const paymentLoading = ref(false); const errorMessage = ref(''); const notice = ref('')
const statusLabel = (value: number) => ({ 1: '待支付', 2: '已预约', 3: '已签到', 4: '就诊中', 5: '已完成', 6: '已取消', 7: '医生停诊取消', 8: '已过期', 9: '已退款' }[value] || '处理中')
const load = async () => { try { const id = Number(route.params.id); item.value = await getPatientAppointment(id); try { payment.value = await getAppointmentPayment(id) } catch (error) { if (!(error instanceof ApiError) || error.status !== 404) throw error } } catch (error) { errorMessage.value = error instanceof ApiError ? error.message : '预约详情加载失败，请稍后重试。' } finally { loading.value = false } }
const findPayment = async () => { paymentLoading.value = true; errorMessage.value = ''; try { const record = await getPayment(Number(paymentId.value)); if (record.appointment_id !== Number(route.params.id)) throw new Error('该支付记录不属于当前预约。'); payment.value = record } catch (error) { errorMessage.value = error instanceof ApiError ? error.message : '支付记录加载失败，请核对编号。' } finally { paymentLoading.value = false } }
const act = async (type: 'pay' | 'check-in' | 'cancel' | 'refund') => { saving.value = true; errorMessage.value = ''; notice.value = ''; try { const id = Number(route.params.id); if (type === 'pay') payment.value = await payAppointment(id); if (type === 'check-in') await checkInPatientAppointment(id); if (type === 'cancel') await cancelPatientAppointment(id); if (type === 'refund' && payment.value) await refundPayment(payment.value.id); notice.value = type === 'pay' ? '支付成功' : type === 'check-in' ? '签到成功' : type === 'refund' ? '退款已提交' : '预约已取消'; await load() } catch (error) { errorMessage.value = error instanceof ApiError ? error.message : '操作失败，请稍后重试。' } finally { saving.value = false } }
onMounted(() => { if (isAdmin.value) loading.value = false; else void load() })
</script>
<template><div class="page"><RouterLink class="back" to="/patient/appointments"><ArrowLeft :size="16" />返回我的预约</RouterLink><header><p>预约详情</p><h1>{{ item?.doctor_name || '预约详情' }}</h1></header><div v-if="isAdmin" class="notice info"><CircleAlert :size="16" />管理员可以浏览患者页面；预约详情请在管理工作台的“预约查询”中查看。</div><div v-else-if="loading" class="state">正在加载详情…</div><template v-else-if="item"><div v-if="notice" class="notice success">{{ notice }}</div><div v-if="errorMessage" class="notice error"><CircleAlert :size="16" />{{ errorMessage }}</div><section class="card"><div><span>预约编号</span><strong>{{ item.appointment_no || item.id }}</strong></div><div><span>就诊日期</span><strong>{{ item.appointment_date || '未填写' }}</strong></div><div><span>状态</span><strong>{{ statusLabel(item.status) }}</strong></div><div><span>费用</span><strong>¥{{ item.fee ?? '0.00' }}</strong></div><div class="wide"><span>备注</span><strong>{{ item.remark || '暂无备注' }}</strong></div></section><div class="actions"><button v-if="item.status === 1" type="button" :disabled="saving" @click="act('pay')"><CreditCard :size="16" />支付</button><button v-if="item.status === 2" type="button" :disabled="saving" @click="act('check-in')"><LogIn :size="16" />签到</button><button v-if="item.status === 1 || item.status === 2" class="danger" type="button" :disabled="saving" @click="act('cancel')">取消预约</button><RouterLink v-if="payment" class="payment-link" :to="`/patient/payments/${payment.id}`">查看支付记录</RouterLink><button v-if="payment && payment.status === 2" class="danger" type="button" :disabled="saving" @click="act('refund')"><RotateCcw :size="16" />退款</button></div><form class="payment-lookup" @submit.prevent="findPayment"><label>已有支付记录编号<input v-model="paymentId" type="number" min="1" required /></label><button type="submit" :disabled="paymentLoading"><Search :size="15" />{{ paymentLoading ? '查询中' : '查询支付记录' }}</button></form></template></div></template>
<style scoped>.page{width:min(100% - 48px,820px);margin:0 auto;padding:72px 0 110px}.back{display:inline-flex;align-items:center;gap:7px;color:#2563eb;font-size:13px;text-decoration:none}.page header{margin:28px 0 24px}.page header p{color:#2563eb;font-size:12px;font-weight:700}.page h1{margin-top:8px;font-size:30px}.card{padding:24px;display:grid;grid-template-columns:repeat(2,1fr);gap:18px;background:#fff;border:1px solid #e2e8f0;border-radius:8px}.card div{display:grid;gap:6px}.card span{color:#64748b;font-size:12px}.card strong{font-size:14px}.wide{grid-column:1/-1}.actions,.payment-lookup{display:flex;gap:9px;margin-top:18px}.actions button,.payment-lookup button{min-height:40px;padding:0 14px;display:inline-flex;align-items:center;gap:7px;color:#fff;background:#2563eb;border:0;border-radius:6px;cursor:pointer}.actions .danger{color:#b91c1c;background:#fee2e2}.payment-lookup{align-items:end;padding-top:16px;border-top:1px solid #e2e8f0}.payment-lookup label{display:grid;gap:6px;color:#475569;font-size:12px}.payment-lookup input{min-height:40px;padding:0 10px;border:1px solid #dbe3ec;border-radius:6px}.notice{margin-bottom:16px;padding:12px 14px;border-radius:7px;font-size:13px}.notice.success{color:#166534;background:#dcfce7}.notice.error{color:#b91c1c;background:#fee2e2}.notice.info{color:#1e4f80;background:#e4f0fb}.state{padding:48px;color:#64748b;text-align:center}@media(max-width:620px){.card{grid-template-columns:1fr}.wide{grid-column:auto}.actions,.payment-lookup{flex-wrap:wrap}.actions button,.payment-lookup button{flex:1}.payment-lookup label{width:100%}}
</style>
