<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { ArrowLeft, CircleAlert, Eye, WalletCards } from 'lucide-vue-next'
import { RouterLink } from 'vue-router'
import { ApiError } from '@/api/http'
import { getPatientPayments } from '@/api/payment'
import type { PaymentRecord } from '@/types/user'
const items=ref<PaymentRecord[]>([]);const loading=ref(true);const errorMessage=ref('');const label=(status:number)=>status===2?'已支付':status===5?'已退款':status===1?'待支付':'处理中';onMounted(async()=>{try{items.value=(await getPatientPayments()).items}catch(error){errorMessage.value=error instanceof ApiError?error.message:'支付记录加载失败，请稍后重试。'}finally{loading.value=false}})
</script>
<template><div class="page"><RouterLink class="back" to="/patient/home"><ArrowLeft :size="16"/>返回患者首页</RouterLink><header><p>支付记录</p><h1>我的支付</h1></header><div v-if="loading" class="state">正在加载支付记录…</div><div v-else-if="errorMessage" class="notice"><CircleAlert :size="16"/>{{errorMessage}}</div><div v-else-if="!items.length" class="state">暂无支付记录。</div><div v-else class="list"><article v-for="item in items" :key="item.id"><WalletCards :size="19"/><div><strong>{{item.payment_no}}</strong><small>预约 {{item.appointment_id}} · ¥{{Number(item.amount).toFixed(2)}} · {{label(item.status)}}</small></div><RouterLink class="icon" :to="`/patient/payments/${item.id}`" title="查看支付详情"><Eye :size="15"/></RouterLink></article></div></div></template>
<style scoped>.page{width:min(100% - 48px,900px);margin:0 auto;padding:70px 0}.back{display:inline-flex;align-items:center;gap:7px;color:var(--primary);text-decoration:none;font-size:13px}.page header{margin:28px 0 22px}.page header p{color:var(--primary);font-size:12px;font-weight:700}.page h1{margin-top:8px;font-family:var(--font-serif);font-size:32px}.list{display:grid;gap:8px}.list article{padding:15px;display:flex;align-items:center;gap:10px;background:var(--surface-strong);border:1px solid var(--border);border-radius:7px}.list article>svg{color:var(--primary)}.list strong,.list small{display:block}.list small{margin-top:4px;color:var(--muted);font-size:12px}.icon{margin-left:auto;width:32px;height:32px;display:grid;place-items:center;color:var(--primary);background:var(--primary-soft);border:1px solid var(--border);border-radius:5px}.state{padding:42px;color:var(--muted);text-align:center}.notice{padding:11px;display:flex;gap:7px;color:var(--danger);background:var(--danger-soft);border-radius:6px}</style>
