<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { ArrowLeft, Check, CircleAlert, Eye, Pill } from 'lucide-vue-next'
import { RouterLink, useRoute } from 'vue-router'
import WorkspaceLayout from '@/components/WorkspaceLayout.vue'
import { ApiError } from '@/api/http'
import { getPharmacyPrescriptions } from '@/api/pharmacy'
const route=useRoute();const items=ref<Record<string,unknown>[]>([]);const loading=ref(true);const errorMessage=ref('');const notice=ref('');const status=ref(Number(route.query.status)||0);const statusLabel=(s:number)=>s===1?'草稿':s===2?'待取药':s===3?'已取药':'处理中';const load=async()=>{loading.value=true;try{items.value=await getPharmacyPrescriptions(status.value||undefined)}catch(e){errorMessage.value=e instanceof ApiError?e.message:'处方列表加载失败，请稍后重试。'}finally{loading.value=false}};const rows=items;onMounted(load)
</script>
<template><WorkspaceLayout role="pharmacy"><div class="page"><RouterLink class="back" to="/pharmacy/home"><ArrowLeft :size="16"/>返回药房首页</RouterLink><header><p>药房服务</p><h1>处方取药</h1></header><div class="toolbar"><select v-model.number="status" @change="load"><option :value="0">全部状态</option><option :value="2">待取药</option><option :value="3">已取药</option></select></div><div v-if="notice" class="notice success"><Check :size="16"/>{{notice}}</div><div v-if="errorMessage" class="notice error"><CircleAlert :size="16"/>{{errorMessage}}</div><div v-if="loading" class="state">正在加载处方…</div><div v-else-if="!rows.length" class="state">暂无处方记录。</div><div v-else class="list"><article v-for="entry in rows" :key="Number(entry.id)"><Pill :size="20"/><div><strong>{{entry.prescription_no||`处方 ${entry.id}`}}</strong><small>{{entry.patient_name||'患者'}} · {{entry.doctor_name||'医生'}} · {{statusLabel(Number(entry.status))}}</small></div><RouterLink class="icon" :to="`/pharmacy/prescriptions/${entry.id}`" title="查看处方"><Eye :size="16"/></RouterLink></article></div></div></WorkspaceLayout></template>
<style scoped>.page{max-width:980px}.back{display:inline-flex;align-items:center;gap:7px;color:var(--primary);font-size:13px;text-decoration:none}.page header{margin:28px 0 20px}.page header p{color:var(--primary);font-size:12px;font-weight:700}.page h1{margin-top:8px;font-size:30px}.toolbar select{min-height:40px;padding:0 11px;background:var(--surface-strong);border:1px solid var(--border-strong);border-radius:5px}.list{margin-top:18px;display:grid;gap:8px}.list article{padding:16px;display:flex;align-items:center;gap:12px;background:var(--surface-strong);border:1px solid var(--border);border-radius:7px}.list article>svg{color:var(--primary)}.list strong,.list small{display:block}.list small{margin-top:5px;color:var(--muted);font-size:12px}.icon{margin-left:auto;width:34px;height:34px;display:grid;place-items:center;color:var(--primary);background:var(--primary-soft);border:1px solid var(--border);border-radius:5px;cursor:pointer}.detail{margin-top:20px;padding:22px;background:var(--surface-strong);border:1px solid var(--border-strong);border-radius:8px}.detail-head{display:flex;justify-content:space-between;align-items:center}.detail h2{font-family:var(--font-serif);font-size:22px}.detail p{margin-top:10px;color:var(--muted);font-size:13px}.items{margin-top:18px;display:grid;gap:8px}.items div{padding:12px;background:var(--surface);border-radius:5px}.items strong,.items span{display:block}.items span{margin-top:4px;color:var(--muted);font-size:12px}.primary{margin-top:18px;min-height:40px;padding:0 14px;display:inline-flex;align-items:center;gap:7px;color:#fff;background:var(--primary);border:0;border-radius:5px;cursor:pointer}.notice{margin-top:16px;padding:11px;display:flex;gap:7px;align-items:center;border-radius:6px}.notice.success{color:#166534;background:#dcfce7}.notice.error{color:#b91c1c;background:var(--danger-soft)}.state{padding:42px;color:var(--muted);text-align:center}</style>
