<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { ArrowLeft, Check, CircleAlert, Pill } from 'lucide-vue-next'
import { RouterLink, useRoute, useRouter } from 'vue-router'
import WorkspaceLayout from '@/components/WorkspaceLayout.vue'
import { ApiError } from '@/api/http'
import { dispensePharmacyPrescription, getPharmacyPrescription } from '@/api/pharmacy'
const route=useRoute();const router=useRouter();const item=ref<Record<string,unknown>|null>(null);const loading=ref(true);const saving=ref(false);const errorMessage=ref('');const notice=ref('');const entries=computed(()=>Array.isArray(item.value?.items)?item.value?.items as Record<string,unknown>[]:[]);const statusLabel=(status:number)=>status===1?'草稿':status===2?'待取药':status===3?'已取药':'处理中'
onMounted(async()=>{try{item.value=await getPharmacyPrescription(Number(route.params.id))}catch(error){errorMessage.value=error instanceof ApiError?error.message:'处方详情加载失败，请稍后重试。'}finally{loading.value=false}})
const dispense=async()=>{if(!item.value)return;saving.value=true;try{await dispensePharmacyPrescription(Number(item.value.id));notice.value='处方已标记为已取药';item.value={...item.value,status:3};setTimeout(()=>router.replace('/pharmacy/prescriptions'),500)}catch(error){errorMessage.value=error instanceof ApiError?error.message:'取药状态更新失败，请稍后重试。'}finally{saving.value=false}}
</script>
<template><WorkspaceLayout role="pharmacy"><div class="page"><RouterLink class="back" to="/pharmacy/prescriptions"><ArrowLeft :size="16" />返回处方列表</RouterLink><header><p>药房服务</p><h1>处方详情</h1></header><div v-if="loading" class="state">正在加载处方…</div><div v-else-if="errorMessage" class="notice error"><CircleAlert :size="16" />{{errorMessage}}</div><template v-else-if="item"><div v-if="notice" class="notice success"><Check :size="16" />{{notice}}</div><section class="summary"><div><span>处方编号</span><strong>{{item.prescription_no||item.id}}</strong></div><div><span>患者</span><strong>{{item.patient_name||'未返回'}}</strong></div><div><span>联系电话</span><strong>{{item.patient_phone||'未返回'}}</strong></div><div><span>医生</span><strong>{{item.doctor_name||'未返回'}}</strong></div><div><span>状态</span><strong>{{statusLabel(Number(item.status))}}</strong></div></section><section class="items"><h2><Pill :size="18" />药品明细</h2><div v-if="!entries.length" class="state">暂无药品明细。</div><article v-for="entry in entries" :key="Number(entry.id)"><strong>{{entry.drug_name}}</strong><span>{{entry.specification||'未填写规格'}} · {{entry.dosage}} · {{entry.frequency}} · {{entry.days}} 天 · 数量 {{entry.quantity}}</span><p v-if="entry.remark">{{entry.remark}}</p></article></section><button v-if="Number(item.status)===2" class="primary" type="button" :disabled="saving" @click="dispense"><Check :size="16" />{{saving?'处理中':'确认已取药'}}</button></template></div></WorkspaceLayout></template>
<style scoped>.page{max-width:900px}.back{display:inline-flex;align-items:center;gap:7px;color:var(--primary);font-size:13px;text-decoration:none}.page header{margin:28px 0 24px}.page header p{color:var(--primary);font-size:12px;font-weight:700}.page h1{margin-top:8px;font-size:30px}.summary{display:grid;grid-template-columns:repeat(3,1fr);gap:1px;background:var(--border);border:1px solid var(--border);border-radius:8px;overflow:hidden}.summary div{padding:17px;background:var(--surface-strong)}.summary span,.summary strong{display:block}.summary span{color:var(--muted);font-size:12px}.summary strong{margin-top:6px;font-size:14px}.items{margin-top:24px}.items h2{display:flex;align-items:center;gap:7px;font-size:18px}.items article{margin-top:9px;padding:15px;background:var(--surface-strong);border:1px solid var(--border);border-radius:7px}.items strong,.items span,.items p{display:block}.items span{margin-top:5px;color:var(--muted);font-size:12px}.items p{margin-top:7px;color:var(--ink);font-size:13px}.primary{margin-top:18px;min-height:42px;padding:0 14px;display:inline-flex;align-items:center;gap:7px;color:#fff;background:var(--primary);border:0;border-radius:5px;cursor:pointer}.notice{padding:12px;display:flex;gap:8px;align-items:center;border-radius:6px}.success{color:#166534;background:#dcfce7}.error{color:var(--danger);background:var(--danger-soft)}.state{padding:42px;color:var(--muted);text-align:center}@media(max-width:700px){.summary{grid-template-columns:repeat(2,1fr)}}@media(max-width:460px){.summary{grid-template-columns:1fr}}
</style>
