<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { ArrowLeft, Bell, CircleAlert } from 'lucide-vue-next'
import { RouterLink } from 'vue-router'
import { ApiError } from '@/api/http'
import { getPublicAnnouncements } from '@/api/announcement'
const items=ref<Record<string,unknown>[]>([]);const loading=ref(true);const errorMessage=ref('');onMounted(async()=>{try{items.value=await getPublicAnnouncements()}catch(e){errorMessage.value=e instanceof ApiError?e.message:'公告加载失败，请稍后重试。'}finally{loading.value=false}})
</script>
<template><div class="page"><RouterLink class="back" to="/"><ArrowLeft :size="16"/>返回首页</RouterLink><header><p>服务信息</p><h1>医院公告</h1></header><div v-if="loading" class="state">正在加载公告…</div><div v-else-if="errorMessage" class="notice"><CircleAlert :size="16"/>{{errorMessage}}</div><div v-else-if="!items.length" class="state">暂无公告。</div><template v-else><RouterLink v-for="item in items" :key="Number(item.id)" class="announcement" :to="`/announcements/${item.id}`"><Bell :size="18"/><div><h2>{{item.title}}</h2><small>{{item.published_at||''}}</small><p>{{item.content}}</p></div></RouterLink></template></div></template>
<style scoped>.page{width:min(100% - 40px,900px);margin:0 auto;padding:50px 0}.back{display:inline-flex;align-items:center;gap:7px;color:var(--primary);font-size:13px;text-decoration:none}.page header{margin:28px 0 22px}.page header p{color:var(--primary);font-size:12px;font-weight:700}.page h1{margin-top:8px;font-family:var(--font-serif);font-size:32px}.announcement{margin-top:10px;padding:18px;display:flex;gap:12px;color:inherit;text-decoration:none;background:var(--surface-strong);border:1px solid var(--border);border-radius:7px}.announcement:hover{border-color:var(--primary)}.announcement>svg{color:var(--primary);margin-top:3px}.page h2{font-size:17px}.page small{display:block;margin-top:5px;color:var(--muted);font-size:12px}.announcement p{margin-top:10px;color:var(--ink);font-size:13px;line-height:1.7;white-space:pre-wrap;display:-webkit-box;-webkit-line-clamp:3;-webkit-box-orient:vertical;overflow:hidden}.state{padding:40px;color:var(--muted);text-align:center}.notice{padding:11px;display:flex;gap:7px;color:var(--danger);background:var(--danger-soft);border-radius:6px}</style>
