<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { ArrowLeft, CircleAlert, Stethoscope } from 'lucide-vue-next'
import { RouterLink, useRoute } from 'vue-router'
import { ApiError } from '@/api/http'
import { getPublicDoctor } from '@/api/public-medical'
import type { PublicDoctor } from '@/types/user'
const route = useRoute(); const doctor = ref<PublicDoctor | null>(null); const loading = ref(true); const errorMessage = ref('')
onMounted(async () => { try { doctor.value = await getPublicDoctor(Number(route.params.id)) } catch (error) { errorMessage.value = error instanceof ApiError ? error.message : '医生信息加载失败，请稍后重试。' } finally { loading.value = false } })
</script>
<template><div class="role-page"><RouterLink class="back" to="/patient/doctors"><ArrowLeft :size="16" />返回医生列表</RouterLink><div v-if="loading" class="state">正在加载医生信息…</div><div v-else-if="errorMessage" class="notice"><CircleAlert :size="16" />{{ errorMessage }}</div><article v-else-if="doctor" class="doctor-card"><span class="doctor-icon"><Stethoscope :size="30" /></span><p>医生资料</p><h1>{{ doctor.real_name }}</h1><h2>{{ doctor.title || '医生' }}</h2><div class="facts"><span>医生工号<strong>{{ doctor.doctor_no }}</strong></span><span>挂号费<strong>¥{{ Number(doctor.consultation_fee).toFixed(2) }}</strong></span></div><section><h3>擅长方向</h3><p>{{ doctor.specialty || '暂未填写' }}</p></section><section><h3>个人简介</h3><p>{{ doctor.introduction || '暂未填写' }}</p></section><RouterLink class="primary" :to="`/patient/schedules?doctor_id=${doctor.id}`">查看可预约排班</RouterLink></article></div></template>
<style scoped>.role-page{width:min(100% - 48px,760px);margin:0 auto;padding:60px 0 100px}.back{display:inline-flex;align-items:center;gap:7px;color:var(--primary);font-size:13px;text-decoration:none}.doctor-card{margin-top:28px;padding:36px;background:#fff;border:1px solid var(--border);border-radius:8px}.doctor-icon{width:60px;height:60px;display:grid;place-items:center;color:var(--primary);background:var(--primary-soft);border-radius:8px}.doctor-card>p{margin-top:30px;color:var(--primary);font-size:12px;font-weight:650}.doctor-card h1{margin-top:10px;font-family:var(--font-serif);font-size:42px;font-weight:500}.doctor-card h2{margin-top:8px;color:var(--muted);font-size:15px;font-weight:500}.facts{margin-top:28px;display:flex;gap:40px}.facts span,.facts strong{display:block}.facts span{color:var(--muted);font-size:12px}.facts strong{margin-top:5px;color:var(--ink);font-size:16px}.doctor-card section{margin-top:28px;padding-top:20px;border-top:1px solid var(--border)}.doctor-card h3{font-size:14px}.doctor-card section p{margin-top:9px;color:var(--muted);line-height:1.8;font-size:13px}.primary{margin-top:30px;min-height:44px;padding:0 18px;display:inline-flex;align-items:center;color:#fff;background:var(--primary);border-radius:5px;text-decoration:none}.state{padding:48px;color:var(--muted);text-align:center}.notice{margin-top:20px;padding:13px;display:flex;gap:8px;align-items:center;color:var(--danger);background:var(--danger-soft);border-radius:6px}@media(max-width:620px){.role-page{width:calc(100% - 28px);padding:42px 0 72px}.doctor-card{padding:24px}.doctor-card h1{font-size:36px}.facts{gap:24px}}
</style>
