<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { CalendarDays, CircleAlert } from 'lucide-vue-next'
import { RouterLink, useRoute } from 'vue-router'
import { ApiError } from '@/api/http'
import { getPublicDepartments } from '@/api/department'
import { getPublicSchedules } from '@/api/public-medical'
import type { Department, PublicSchedule } from '@/types/user'
const route = useRoute(); const departments = ref<Department[]>([]); const schedules = ref<PublicSchedule[]>([]); const loading = ref(true); const errorMessage = ref(''); const departmentId = ref<number | undefined>(route.query.department_id ? Number(route.query.department_id) : undefined); const doctorId = ref<number | undefined>(route.query.doctor_id ? Number(route.query.doctor_id) : undefined); const date = ref(''); const period = ref<number | undefined>(undefined)
const periodLabel = (value:number) => value===1?'上午':value===2?'下午':'晚上'
const load = async () => { loading.value=true; errorMessage.value=''; try { schedules.value=await getPublicSchedules({department_id:departmentId.value,doctor_id:doctorId.value,schedule_date:date.value,period:period.value}) } catch(error) { errorMessage.value=error instanceof ApiError?error.message:'排班信息加载失败，请稍后重试。' } finally { loading.value=false } }
onMounted(async()=>{ try{departments.value=await getPublicDepartments()}catch{}; await load() })
</script>
<template><div class="role-page"><header class="role-heading"><p>预约准备</p><h1>可预约排班</h1><span>选择合适的科室、医生和就诊时间。</span></header><form class="filters" @submit.prevent="load"><select v-model.number="departmentId"><option :value="undefined">全部科室</option><option v-for="item in departments" :key="item.id" :value="item.id">{{ item.name }}</option></select><input v-model="date" type="date" /><select v-model.number="period"><option :value="undefined">全部时段</option><option :value="1">上午</option><option :value="2">下午</option><option :value="3">晚上</option></select><button class="primary" type="submit">筛选</button></form><div v-if="loading" class="state">正在加载排班…</div><div v-else-if="errorMessage" class="notice"><CircleAlert :size="16" />{{ errorMessage }}</div><div v-else-if="!schedules.length" class="state">暂无可预约排班。</div><div v-else class="schedule-list"><RouterLink v-for="item in schedules" :key="item.id" class="schedule-item" :to="`/patient/schedules/${item.id}`"><span class="schedule-icon"><CalendarDays :size="21" /></span><span><strong>{{ item.doctor_name }}</strong><small>{{ item.schedule_date }} · {{ periodLabel(item.period) }} · {{ item.start_time.slice(0,5) }}—{{ item.end_time.slice(0,5) }}</small></span><em>剩余 {{ item.remaining_count }} 号</em></RouterLink></div></div></template>
<style scoped>.role-page{width:min(100% - 48px,960px);margin:0 auto;padding:72px 0 110px}.role-heading p{color:var(--primary);font-size:12px;font-weight:650}.role-heading h1{margin-top:12px;font-family:var(--font-serif);font-size:46px;font-weight:500}.role-heading span{display:block;margin-top:12px;color:var(--muted);font-size:14px}.filters{margin-top:36px;display:grid;grid-template-columns:1fr 1fr 1fr auto;gap:10px}.filters input,.filters select{min-height:44px;padding:0 11px;background:#fff;border:1px solid var(--border);border-radius:5px;color:var(--ink)}.primary{min-height:44px;padding:0 20px;color:#fff;background:var(--primary);border:0;border-radius:5px;cursor:pointer}.schedule-list{margin-top:24px;display:grid;gap:10px}.schedule-item{padding:18px;display:grid;grid-template-columns:40px 1fr auto;gap:13px;align-items:center;color:var(--ink);background:#fff;border:1px solid var(--border);border-radius:7px;text-decoration:none}.schedule-icon{width:40px;height:40px;display:grid;place-items:center;color:var(--primary);background:var(--primary-soft);border-radius:6px}.schedule-item strong,.schedule-item small{display:block}.schedule-item small,.schedule-item em{margin-top:5px;color:var(--muted);font-size:12px;font-style:normal}.schedule-item em{color:var(--primary)}.state{padding:48px;color:var(--muted);text-align:center}.notice{margin-top:20px;padding:13px;display:flex;gap:8px;align-items:center;color:var(--danger);background:var(--danger-soft);border-radius:6px}@media(max-width:680px){.role-page{width:calc(100% - 28px);padding:48px 0 72px}.role-heading h1{font-size:38px}.filters{grid-template-columns:1fr}.schedule-item{grid-template-columns:40px 1fr}.schedule-item em{grid-column:2}}
</style>
