<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { ArrowLeft, CalendarCheck, Check, CircleAlert, Clock3 } from 'lucide-vue-next'
import { RouterLink, useRoute } from 'vue-router'
import { ApiError } from '@/api/http'
import { getPublicDoctor, getPublicSchedule, getPublicScheduleSlots } from '@/api/public-medical'
import { createAppointment } from '@/api/appointment'
import type { PublicSchedule, PublicSlot } from '@/types/user'
const route=useRoute(); const schedule=ref<PublicSchedule|null>(null); const slots=ref<PublicSlot[]>([]); const selectedSlot=ref<number|null>(null); const loading=ref(true); const saving=ref(false); const notice=ref(''); const errorMessage=ref(''); const periodLabel=(value:number)=>value===1?'上午':value===2?'下午':'晚上'
onMounted(async()=>{try{const id=Number(route.params.id);const [data,availableSlots]=await Promise.all([getPublicSchedule(id),getPublicScheduleSlots(id)]);const doctor=await getPublicDoctor(data.doctor_id);schedule.value={...data,doctor_name:doctor.real_name,remaining_count:data.remaining_count ?? data.total_count-data.booked_count};slots.value=availableSlots}catch(error){errorMessage.value=error instanceof ApiError?error.message:'排班信息加载失败，请稍后重试。'}finally{loading.value=false}})
const book = async () => { if (!schedule.value) return; saving.value = true; errorMessage.value = ''; notice.value = ''; try { await createAppointment({ schedule_id: schedule.value.id, slot_id: selectedSlot.value, request_no: `CLARK-${Date.now()}-${Math.random().toString(36).slice(2, 8)}` }); notice.value = '预约成功，已为您保留号源'; schedule.value.remaining_count = Math.max(0, schedule.value.remaining_count - 1); if (selectedSlot.value !== null) slots.value = slots.value.filter((slot) => slot.id !== selectedSlot.value); selectedSlot.value = null } catch (error) { errorMessage.value = error instanceof ApiError ? error.message : '预约失败，请稍后重试。' } finally { saving.value = false } }
</script>
<template><div class="role-page"><RouterLink class="back" to="/patient/schedules"><ArrowLeft :size="16" />返回排班列表</RouterLink><div v-if="loading" class="state">正在加载排班…</div><div v-else-if="errorMessage" class="notice"><CircleAlert :size="16" />{{ errorMessage }}</div><article v-else-if="schedule" class="schedule-card"><p>门诊时间</p><h1>{{ schedule.doctor_name }}</h1><h2>{{ schedule.schedule_date }} · {{ periodLabel(schedule.period) }}</h2><div v-if="notice" class="notice success"><Check :size="16" />{{ notice }}</div><div class="facts"><span>时段<strong>{{ schedule.start_time.slice(0,5) }}—{{ schedule.end_time.slice(0,5) }}</strong></span><span>剩余号源<strong>{{ schedule.remaining_count }}</strong></span><span>挂号费<strong>¥{{ Number(schedule.fee).toFixed(2) }}</strong></span></div><section><h3>可选时间段</h3><div v-if="!slots.length" class="empty">暂无可用时间段。</div><div v-else class="slots"><button v-for="slot in slots" :key="slot.id" type="button" :class="{selected:selectedSlot===slot.id}" @click="selectedSlot=slot.id"><Clock3 :size="15" />{{ slot.start_time.slice(0,5) }}—{{ slot.end_time.slice(0,5) }}</button></div><button class="book" type="button" :disabled="saving || !schedule.remaining_count" @click="book"><CalendarCheck :size="17" />{{ saving ? '预约中' : '立即预约' }}</button><div v-if="errorMessage" class="notice"><CircleAlert :size="16" />{{ errorMessage }}</div></section></article></div></template>
<style scoped>.role-page{width:min(100% - 48px,760px);margin:0 auto;padding:60px 0 100px}.back{display:inline-flex;align-items:center;gap:7px;color:var(--primary);font-size:13px;text-decoration:none}.schedule-card{margin-top:28px;padding:36px;background:#fff;border:1px solid var(--border);border-radius:8px}.schedule-card>p{color:var(--primary);font-size:12px;font-weight:650}.schedule-card h1{margin-top:10px;font-family:var(--font-serif);font-size:42px;font-weight:500}.schedule-card h2{margin-top:8px;color:var(--muted);font-size:15px;font-weight:500}.facts{margin-top:28px;display:flex;gap:30px}.facts span,.facts strong{display:block}.facts span{color:var(--muted);font-size:12px}.facts strong{margin-top:5px;color:var(--ink);font-size:16px}.schedule-card section{margin-top:30px;padding-top:20px;border-top:1px solid var(--border)}.schedule-card h3{font-size:14px}.slots{margin-top:14px;display:flex;flex-wrap:wrap;gap:8px}.slots button{padding:9px 11px;display:inline-flex;align-items:center;gap:6px;color:var(--primary);background:var(--primary-soft);border:1px solid transparent;border-radius:5px;font-size:12px;cursor:pointer}.slots button.selected{border-color:var(--primary);background:#d8f0e6}.book{margin-top:18px;min-height:42px;padding:0 18px;display:inline-flex;align-items:center;gap:7px;color:#fff;background:var(--primary);border:0;border-radius:6px;cursor:pointer}.book:disabled{opacity:.55;cursor:not-allowed}.empty{margin-top:14px;color:var(--muted);font-size:13px}.state{padding:48px;color:var(--muted);text-align:center}.notice{margin-top:20px;padding:13px;display:flex;gap:8px;align-items:center;color:var(--danger);background:var(--danger-soft);border-radius:6px}.notice.success{color:#166534;background:#dcfce7}@media(max-width:620px){.role-page{width:calc(100% - 28px);padding:42px 0 72px}.schedule-card{padding:24px}.schedule-card h1{font-size:36px}.facts{gap:18px;flex-wrap:wrap}}
</style>
