<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { Check, CircleAlert, PhoneCall, RotateCcw, UserX, Users } from 'lucide-vue-next'
import WorkspaceLayout from '@/components/WorkspaceLayout.vue'
import { ApiError } from '@/api/http'
import { getRegistrationQueue } from '@/api/registration'
import { callRegistrationQueue, markRegistrationNoShow, requeueRegistration } from '@/api/registration-extended'
import { useAuth } from '@/stores/auth'
import type { AppointmentRecord } from '@/types/user'
const {currentUser}=useAuth();const isAdmin=computed(()=>currentUser.value?.role_codes.includes('ADMIN')||currentUser.value?.primary_role==='ADMIN');const items=ref<AppointmentRecord[]>([]);const loading=ref(true);const errorMessage=ref('');const notice=ref('');const actionId=ref(0)
const localDate=()=>{const now=new Date();const year=now.getFullYear();const month=String(now.getMonth()+1).padStart(2,'0');const day=String(now.getDate()).padStart(2,'0');return `${year}-${month}-${day}`}
const load=async()=>{if(isAdmin.value){loading.value=false;return}try{const today=localDate();items.value=(await getRegistrationQueue()).filter((item)=>item.appointment_date===today)}catch(error){errorMessage.value=error instanceof ApiError?error.message:'候诊队列加载失败，请稍后重试。'}finally{loading.value=false}}
const act=async(id:number,type:'call'|'no-show'|'requeue')=>{actionId.value=id;errorMessage.value='';try{if(type==='call')await callRegistrationQueue(id);if(type==='no-show')await markRegistrationNoShow(id);if(type==='requeue')await requeueRegistration(id);notice.value=type==='call'?'已呼叫患者':type==='no-show'?'已标记过号':'已重新排队';await load()}catch(error){errorMessage.value=error instanceof ApiError?error.message:'队列操作失败，请稍后重试。'}finally{actionId.value=0}}
onMounted(load)
</script>
<template><WorkspaceLayout role="registration"><div class="page"><p>挂号服务</p><h1>候诊队列</h1><div v-if="isAdmin" class="notice info"><CircleAlert :size="16"/>管理员可以浏览挂号员页面；候诊操作请使用挂号员账号。</div><template v-else><div v-if="notice" class="notice success"><Check :size="16"/>{{notice}}</div><div v-if="loading" class="state">正在加载队列…</div><div v-else-if="errorMessage" class="notice"><CircleAlert :size="16"/>{{errorMessage}}</div><div v-else-if="!items.length" class="state">当前暂无候诊患者。</div><div v-else class="queue"><article v-for="item in items" :key="item.id"><span class="number">{{item.queue_no||'—'}}</span><div><strong>{{item.appointment_no||`预约 ${item.id}`}}</strong><small>{{item.appointment_date||'未填写日期'}} · {{item.remark||'已完成签到'}}</small></div><Users :size="18"/><div class="actions"><button type="button" :disabled="actionId===item.id" @click="act(item.id,'call')"><PhoneCall :size="14"/>呼叫</button><button type="button" :disabled="actionId===item.id" @click="act(item.id,'no-show')"><UserX :size="14"/>过号</button><button type="button" :disabled="actionId===item.id" @click="act(item.id,'requeue')"><RotateCcw :size="14"/>重排</button></div></article></div></template></div></WorkspaceLayout></template>
<style scoped>.page{max-width:820px}.page>p{color:#2563eb;font-size:12px;font-weight:700}.page h1{margin-top:8px;font-size:30px}.queue{margin-top:28px;display:grid;gap:9px}.queue article{padding:17px;display:flex;align-items:center;gap:14px;background:#fff;border:1px solid #e2e8f0;border-radius:7px}.number{width:38px;height:38px;display:grid;place-items:center;color:#2563eb;background:#dbeafe;border-radius:50%;font-weight:700}.queue strong,.queue small{display:block}.queue small{margin-top:5px;color:#64748b;font-size:12px}.queue svg{margin-left:auto;color:#2563eb}.state{padding:48px;color:#64748b;text-align:center}.notice{margin-top:20px;padding:13px;display:flex;gap:8px;align-items:center;color:#b91c1c;background:#fee2e2;border-radius:6px}.notice.info{color:#1e4f80;background:#e4f0fb}
</style>
