<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { Check, CircleAlert, LogIn, XCircle } from 'lucide-vue-next'
import WorkspaceLayout from '@/components/WorkspaceLayout.vue'
import { ApiError } from '@/api/http'
import { cancelAppointment, checkInAppointment, getRegistrationAppointmentsPage } from '@/api/registration'
import { refundRegistrationAppointment } from '@/api/registration-extended'
import { useAuth } from '@/stores/auth'
import type { AppointmentRecord } from '@/types/user'
const { currentUser } = useAuth();const isAdmin=computed(()=>currentUser.value?.role_codes.includes('ADMIN')||currentUser.value?.primary_role==='ADMIN')
const items=ref<AppointmentRecord[]>([]);const page=ref(1);const total=ref(0);const pageSize=20;const loading=ref(true);const errorMessage=ref('');const notice=ref('');const actionId=ref(0)
const statusLabel=(status:number)=>status===1?'待确认':status===2?'待签到':status===3?'已签到':status===6?'已取消':'处理中'
const load=async()=>{if(isAdmin.value){loading.value=false;return}loading.value=true;try{const result=await getRegistrationAppointmentsPage(page.value,pageSize);items.value=result.items;total.value=result.total}catch(error){errorMessage.value=error instanceof ApiError?error.message:'预约加载失败，请稍后重试。'}finally{loading.value=false}}
const act=async(id:number,type:'checkin'|'cancel'|'refund')=>{notice.value='';errorMessage.value='';actionId.value=id;try{if(type==='checkin')await checkInAppointment(id);else if(type==='refund')await refundRegistrationAppointment(id);else{const reason=window.prompt('请输入取消原因','患者现场申请取消')?.trim();if(!reason){actionId.value=0;return}await cancelAppointment(id,reason)}notice.value=type==='checkin'?'签到成功':type==='refund'?'退款已办理':'预约已取消';await load()}catch(error){errorMessage.value=error instanceof ApiError?error.message:'操作失败，请稍后重试。'}finally{actionId.value=0}}
const pageCount=()=>Math.max(1,Math.ceil(total.value/pageSize));const changePage=(delta:number)=>{const next=page.value+delta;if(next<1||next>pageCount())return;page.value=next;void load()}
onMounted(load)
</script>
<template><WorkspaceLayout role="registration"><div class="page"><p>挂号服务</p><h1>预约处理</h1><div v-if="isAdmin" class="notice info"><CircleAlert :size="16"/>管理员可以浏览挂号员页面；全部预约请在管理工作台中查询。</div><template v-else><div v-if="notice" class="notice success"><Check :size="16"/>{{notice}}</div><div v-if="errorMessage" class="notice error"><CircleAlert :size="16"/>{{errorMessage}}</div><div v-if="loading" class="state">正在加载预约…</div><div v-else-if="!items.length" class="state">暂无待处理预约。</div><div v-else class="list"><article v-for="item in items" :key="item.id"><div><strong>{{item.appointment_no||`预约 ${item.id}`}}</strong><span>{{item.appointment_date||'未填写日期'}} · 队列号 {{item.queue_no||'—'}} · {{statusLabel(item.status)}}</span></div><div class="actions"><button v-if="item.status===2" type="button" :disabled="actionId===item.id" @click="act(item.id,'checkin')"><LogIn :size="15"/>签到</button><button v-if="item.status===1||item.status===2" class="cancel" type="button" :disabled="actionId===item.id" @click="act(item.id,'cancel')"><XCircle :size="15"/>取消</button><button v-if="item.status===6" class="refund" type="button" :disabled="actionId===item.id" @click="act(item.id,'refund')">办理退款</button></div></article></div><div v-if="!loading && items.length" class="pagination"><button type="button" :disabled="page<=1" @click="changePage(-1)">上一页</button><span>第 {{page}} / {{pageCount()}} 页，共 {{total}} 条</span><button type="button" :disabled="page>=pageCount()" @click="changePage(1)">下一页</button></div></template></div></WorkspaceLayout></template>
<style scoped>.page{max-width:980px}.page>p{color:#2563eb;font-size:12px;font-weight:700}.page h1{margin-top:8px;font-size:30px}.list{margin-top:28px;display:grid;gap:10px}.list article{padding:17px;display:flex;justify-content:space-between;align-items:center;gap:14px;background:#fff;border:1px solid #e2e8f0;border-radius:7px}.list strong,.list span{display:block}.list span{margin-top:5px;color:#64748b;font-size:12px}.actions{display:flex;gap:7px}.actions button{min-height:34px;padding:0 11px;display:inline-flex;align-items:center;gap:6px;color:#fff;background:#2563eb;border:0;border-radius:5px;cursor:pointer;font-size:12px}.actions .cancel{color:#b91c1c;background:#fee2e2}.notice{margin-top:18px;padding:12px;display:flex;gap:8px;align-items:center;border-radius:6px;font-size:13px}.notice.success{color:#166534;background:#dcfce7}.notice.error{color:#b91c1c;background:#fee2e2}.notice.info{color:#1e4f80;background:#e4f0fb}.pagination{margin-top:18px;display:flex;justify-content:center;align-items:center;gap:12px;color:#64748b;font-size:12px}.pagination button{min-height:34px;padding:0 10px;background:#fff;border:1px solid #dbe3ec;border-radius:5px;cursor:pointer}.pagination button:disabled{opacity:.5}.state{padding:48px;color:#64748b;text-align:center}@media(max-width:620px){.list article{align-items:flex-start;flex-direction:column}.actions{width:100%}.actions button{flex:1;justify-content:center}}
</style>


