<script setup lang="ts">
import { ref } from 'vue'
import { CircleAlert, Search, UserRound } from 'lucide-vue-next'
import WorkspaceLayout from '@/components/WorkspaceLayout.vue'
import { RouterLink } from 'vue-router'
import { ApiError } from '@/api/http'
import { getRegistrationPatients } from '@/api/registration-extended'
const keyword=ref('');const items=ref<Record<string,unknown>[]>([]);const loading=ref(false);const errorMessage=ref('');const load=async()=>{loading.value=true;try{items.value=await getRegistrationPatients(keyword.value)}catch(e){errorMessage.value=e instanceof ApiError?e.message:'患者查询失败，请稍后重试。'}finally{loading.value=false}}
</script>
<template><WorkspaceLayout role="registration"><div class="page"><header><p>挂号服务</p><h1>患者检索</h1></header><form class="search" @submit.prevent="load"><input v-model="keyword" placeholder="姓名、手机号或证件号码"/><button type="submit"><Search :size="16"/>查询</button></form><div v-if="errorMessage" class="notice"><CircleAlert :size="16"/>{{errorMessage}}</div><div v-if="loading" class="state">正在查询患者…</div><div v-else-if="!items.length" class="state">暂无患者记录。</div><div v-else class="list"><article v-for="item in items" :key="Number(item.id)"><UserRound :size="20"/><div><strong>{{item.real_name}}</strong><small>患者编号 {{item.id}} · {{item.phone||'未填写电话'}}</small></div><RouterLink class="detail-link" :to="`/registration/patients/${item.id}`">查看详情</RouterLink></article></div></div></WorkspaceLayout></template>
<style scoped>.page{max-width:900px}.page header{margin-bottom:22px}.page header p{color:var(--primary);font-size:12px;font-weight:700}.page h1{margin-top:8px;font-size:30px}.search{display:flex;gap:8px}.search input{flex:1;min-height:42px;padding:0 11px;border:1px solid var(--border-strong);border-radius:5px}.search button{min-height:42px;padding:0 14px;display:inline-flex;align-items:center;gap:6px;color:#fff;background:var(--primary);border:0;border-radius:5px;cursor:pointer}.list{margin-top:18px;display:grid;gap:8px}.list article{padding:15px;display:flex;gap:11px;align-items:center;background:var(--surface-strong);border:1px solid var(--border);border-radius:7px}.list article>svg{color:var(--primary)}.list strong,.list small{display:block}.list small{margin-top:4px;color:var(--muted);font-size:12px}.detail-link{margin-left:auto;color:var(--primary);font-size:12px;text-decoration:none}.notice{margin-top:14px;padding:11px;display:flex;gap:7px;color:var(--danger);background:var(--danger-soft);border-radius:6px}.state{padding:40px;color:var(--muted)}</style>
