<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { Bell, Check, CircleAlert } from 'lucide-vue-next'
import { ApiError } from '@/api/http'
import { getSystemNotifications, readSystemNotification } from '@/api/system'
const items=ref<Record<string,unknown>[]>([]);const loading=ref(true);const errorMessage=ref('');const notice=ref('');const load=async()=>{try{items.value=await getSystemNotifications()}catch(e){errorMessage.value=e instanceof ApiError?e.message:'通知加载失败，请稍后重试。'}finally{loading.value=false}};const read=async(id:number)=>{try{await readSystemNotification(id);notice.value='通知已标记为已读';await load()}catch(e){errorMessage.value=e instanceof ApiError?e.message:'操作失败，请稍后重试。'}};onMounted(load)
</script>
<template><div class="page"><header><p>消息中心</p><h1>我的通知</h1></header><div v-if="notice" class="notice success"><Check :size="16"/>{{notice}}</div><div v-if="errorMessage" class="notice error"><CircleAlert :size="16"/>{{errorMessage}}</div><div v-if="loading" class="state">正在加载通知…</div><div v-else-if="!items.length" class="state">暂无新通知。</div><div v-else class="list"><article v-for="item in items" :key="Number(item.id)" :class="{ unread: Number(item.read_status)===0 }"><Bell :size="18"/><div><strong>{{item.title||item.notification_type||'系统通知'}}</strong><small>{{item.created_at||''}}</small><p>{{item.content||item.message||''}}</p></div><button v-if="Number(item.read_status)===0" type="button" @click="read(Number(item.id))"><Check :size="15"/>标为已读</button></article></div></div></template>
<style scoped>.page{width:min(100% - 40px,900px);margin:0 auto;padding:55px 0}.page header{margin-bottom:22px}.page header p{color:var(--primary);font-size:12px;font-weight:700}.page h1{margin-top:8px;font-family:var(--font-serif);font-size:32px}.list{display:grid;gap:9px}.list article{padding:16px;display:flex;gap:10px;align-items:flex-start;background:var(--surface-strong);border:1px solid var(--border);border-radius:7px}.list article.unread{border-color:var(--primary)}.list article>svg{color:var(--primary)}.list strong,.list small,.list p{display:block}.list small{margin-top:4px;color:var(--muted);font-size:12px}.list p{margin-top:8px;font-size:13px}.list button{margin-left:auto;white-space:nowrap;min-height:32px;padding:0 9px;display:inline-flex;align-items:center;gap:5px;color:var(--primary);background:var(--primary-soft);border:1px solid var(--border);border-radius:5px;cursor:pointer}.notice{margin-bottom:14px;padding:11px;display:flex;gap:7px;align-items:center;border-radius:6px}.success{color:#166534;background:#dcfce7}.error{color:var(--danger);background:var(--danger-soft)}.state{padding:40px;color:var(--muted)}</style>
