import { requestJson } from './http'

const query = (params: Record<string, unknown>) => {
  const search = new URLSearchParams()
  Object.entries(params).forEach(([key, value]) => { if (value !== undefined && value !== null && value !== '') search.set(key, String(value)) })
  return search.toString()
}

export const createAdminPharmacy = (payload: { username: string; password: string }) => requestJson<Record<string, unknown>>('/api/admin/pharmacy', { method: 'POST', body: JSON.stringify(payload) })
export const getAdminUsersPage = (params: { page?: number; page_size?: number; user_type?: number; status?: number; keyword?: string } = {}) => requestJson<Record<string, unknown>>(`/api/admin/users/page${query(params) ? `?${query(params)}` : ''}`, { method: 'GET' })
export const updateAdminUser = (id: number, payload: { username?: string; status?: number }) => requestJson<Record<string, unknown>>(`/api/admin/users/${id}`, { method: 'PUT', body: JSON.stringify(payload) })
export const deleteAdminUser = (id: number) => requestJson<null>(`/api/admin/users/${id}`, { method: 'DELETE' })
export const restoreAdminUser = (id: number) => requestJson<Record<string, unknown>>(`/api/admin/users/${id}/restore`, { method: 'POST' })
export const getAdminUserRolesDetail = (userId: number) => requestJson<Record<string, unknown>[]>(`/api/admin/users/${userId}/roles`, { method: 'GET' })
export const assignAdminRole = (userId: number, role_code: string) => requestJson<Record<string, unknown>>(`/api/admin/users/${userId}/roles`, { method: 'POST', body: JSON.stringify({ role_code }) })
export const removeAdminRole = (userId: number, roleId: number) => requestJson<null>(`/api/admin/users/${userId}/roles/${roleId}`, { method: 'DELETE' })
export const getAdminRoles = () => requestJson<Record<string, unknown>[]>('/api/admin/roles', { method: 'GET' })
export const createAdminRole = (payload: Record<string, unknown>) => requestJson<Record<string, unknown>>('/api/admin/roles', { method: 'POST', body: JSON.stringify(payload) })
export const updateAdminRole = (id: number, payload: Record<string, unknown>) => requestJson<Record<string, unknown>>(`/api/admin/roles/${id}`, { method: 'PUT', body: JSON.stringify(payload) })
export const deleteAdminRole = (id: number) => requestJson<null>(`/api/admin/roles/${id}`, { method: 'DELETE' })
export const getAdminRolePermissions = (id: number) => requestJson<Record<string, unknown>[]>(`/api/admin/roles/${id}/permissions`, { method: 'GET' })
export const assignAdminPermission = (roleId: number, permission_code: string) => requestJson<Record<string, unknown>>(`/api/admin/roles/${roleId}/permissions`, { method: 'POST', body: JSON.stringify({ permission_code }) })
export const removeAdminPermission = (roleId: number, permissionId: number) => requestJson<null>(`/api/admin/roles/${roleId}/permissions/${permissionId}`, { method: 'DELETE' })
export const getAdminPermissions = () => requestJson<Record<string, unknown>[]>('/api/admin/permissions', { method: 'GET' })
export const createAdminPermission = (payload: Record<string, unknown>) => requestJson<Record<string, unknown>>('/api/admin/permissions', { method: 'POST', body: JSON.stringify(payload) })
export const updateAdminPermission = (id: number, payload: Record<string, unknown>) => requestJson<Record<string, unknown>>(`/api/admin/permissions/${id}`, { method: 'PUT', body: JSON.stringify(payload) })
export const deleteAdminPermission = (id: number) => requestJson<null>(`/api/admin/permissions/${id}`, { method: 'DELETE' })
export const getAdminStatistics = () => requestJson<Record<string, unknown>>('/api/admin/statistics', { method: 'GET' })
export const getAdminPayments = (params: { page?: number; page_size?: number; status?: number } = {}) => requestJson<Record<string, unknown>>(`/api/admin/payments${query(params) ? `?${query(params)}` : ''}`, { method: 'GET' })
export const updateAdminAppointment = (id: number, payload: Record<string, unknown>) => requestJson<Record<string, unknown>>(`/api/admin/appointments/${id}`, { method: 'PUT', body: JSON.stringify(payload) })
export const cancelAdminAppointment = (id: number, reason?: string) => requestJson<null>(`/api/admin/appointments/${id}/cancel`, { method: 'POST', body: JSON.stringify(reason ? { reason } : {}) })
export const expireAdminAppointment = (id: number) => requestJson<null>(`/api/admin/appointments/${id}/expire`, { method: 'POST' })
export const stopAdminSchedule = (id: number) => requestJson<null>(`/api/admin/schedules/${id}/stop`, { method: 'POST' })
export const updateAdminScheduleStatus = (id: number, status: number) => requestJson<null>(`/api/admin/schedules/${id}/status`, { method: 'PUT', body: JSON.stringify({ status }) })
export const updateAdminScheduleStop = (id: number) => requestJson<null>(`/api/admin/schedules/${id}/stop`, { method: 'POST' })
export const getNotificationOutbox = (params: { status?: number; limit?: number } = {}) => requestJson<Record<string, unknown>[]>(`/api/admin/notification-outbox${query(params) ? `?${query(params)}` : ''}`, { method: 'GET' })
export const sendNotificationOutbox = (id: number) => requestJson<null>(`/api/admin/notification-outbox/${id}/send`, { method: 'POST' })
export const retryNotificationOutbox = (id: number) => requestJson<null>(`/api/admin/notification-outbox/${id}/retry`, { method: 'POST' })
export const getDataConsistency = () => requestJson<Record<string, unknown>>('/api/admin/data-consistency', { method: 'GET' })
export const repairDataConsistency = () => requestJson<Record<string, unknown>>('/api/admin/data-consistency/repair', { method: 'POST' })
